In [ ]:
!pip install biopython

In [ ]:
import pandas as pd

df = pd.read_csv("csv-AfricanAme-set.csv")

pmids = df["PMID"].dropna().astype(str).tolist()

In [ ]:
from Bio import Entrez

Entrez.email = "mrakkar@sas.upenn.edu"  # REQUIRED

def fetch_abstracts(pmids):
    abstracts = []
    
    for i in range(0, len(pmids), 100):  # batch in chunks
        batch = pmids[i:i+100]
        handle = Entrez.efetch(db="pubmed", id=",".join(batch), rettype="abstract", retmode="text")
        data = handle.read()
        abstracts.extend(data.split("\n\n"))  # rough split
        
    return abstracts

abstracts = fetch_abstracts(pmids)

In [ ]:
from Bio import Entrez
import time

Entrez.email = "mrakkar@sas.upenn.edu"

def fetch_abstract(pmid):
    try:
        handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
        records = Entrez.read(handle)
        
        article = records["PubmedArticle"][0]
        
        abstract = article["MedlineCitation"]["Article"].get("Abstract", {})
        
        if "AbstractText" in abstract:
            return " ".join(abstract["AbstractText"])
        else:
            return ""
        
    except:
        return ""

# Fetch abstracts one by one (safer)
abstract_list = []

for pmid in pmids:
    abstract_list.append(fetch_abstract(pmid))
    time.sleep(0.3)  # avoid hitting rate limits

df["Abstract"] = abstract_list

In [ ]:
df.to_csv("african_amer_abstracts_with_text.csv", index=False)

In [15]:
pmids_small = pmids[:5]  # first 5 PMIDs

abstract_list = []

for pmid in pmids_small:
    abstract_list.append(fetch_abstract(pmid))
    print(f"Fetched PMID {pmid}")  # shows progress

Fetched PMID 41491560
Fetched PMID 41402564
Fetched PMID 41385717
Fetched PMID 41283203
Fetched PMID 41208612

In [16]:
import time

abstract_list = []

for i, pmid in enumerate(pmids):
    abstract_list.append(fetch_abstract(pmid))
    if i % 10 == 0:
        print(f"Fetched {i+1} of {len(pmids)} PMIDs")
    time.sleep(0.3)

Fetched 1 of 1856 PMIDs
Fetched 11 of 1856 PMIDs
Fetched 21 of 1856 PMIDs
Fetched 31 of 1856 PMIDs
Fetched 41 of 1856 PMIDs
Fetched 51 of 1856 PMIDs
Fetched 61 of 1856 PMIDs
Fetched 71 of 1856 PMIDs
Fetched 81 of 1856 PMIDs
Fetched 91 of 1856 PMIDs
Fetched 101 of 1856 PMIDs
Fetched 111 of 1856 PMIDs
Fetched 121 of 1856 PMIDs
Fetched 131 of 1856 PMIDs
Fetched 141 of 1856 PMIDs
Fetched 151 of 1856 PMIDs
Fetched 161 of 1856 PMIDs
Fetched 171 of 1856 PMIDs
Fetched 181 of 1856 PMIDs
Fetched 191 of 1856 PMIDs
Fetched 201 of 1856 PMIDs
Fetched 211 of 1856 PMIDs
Fetched 221 of 1856 PMIDs
Fetched 231 of 1856 PMIDs
Fetched 241 of 1856 PMIDs
Fetched 251 of 1856 PMIDs
Fetched 261 of 1856 PMIDs
Fetched 271 of 1856 PMIDs
Fetched 281 of 1856 PMIDs
Fetched 291 of 1856 PMIDs
Fetched 301 of 1856 PMIDs
Fetched 311 of 1856 PMIDs
Fetched 321 of 1856 PMIDs
Fetched 331 of 1856 PMIDs
Fetched 341 of 1856 PMIDs
Fetched 351 of 1856 PMIDs
Fetched 361 of 1856 PMIDs
Fetched 371 of 1856 PMIDs
Fetched 381 of 1856 PMIDs
Fetched 391 of 1856 PMIDs
Fetched 401 of 1856 PMIDs
Fetched 411 of 1856 PMIDs
Fetched 421 of 1856 PMIDs
Fetched 431 of 1856 PMIDs
Fetched 441 of 1856 PMIDs
Fetched 451 of 1856 PMIDs
Fetched 461 of 1856 PMIDs
Fetched 471 of 1856 PMIDs
Fetched 481 of 1856 PMIDs
Fetched 491 of 1856 PMIDs
Fetched 501 of 1856 PMIDs
Fetched 511 of 1856 PMIDs
Fetched 521 of 1856 PMIDs
Fetched 531 of 1856 PMIDs
Fetched 541 of 1856 PMIDs
Fetched 551 of 1856 PMIDs
Fetched 561 of 1856 PMIDs
Fetched 571 of 1856 PMIDs
Fetched 581 of 1856 PMIDs
Fetched 591 of 1856 PMIDs
Fetched 601 of 1856 PMIDs
Fetched 611 of 1856 PMIDs
Fetched 621 of 1856 PMIDs
Fetched 631 of 1856 PMIDs
Fetched 641 of 1856 PMIDs
Fetched 651 of 1856 PMIDs
Fetched 661 of 1856 PMIDs
Fetched 671 of 1856 PMIDs
Fetched 681 of 1856 PMIDs
Fetched 691 of 1856 PMIDs
Fetched 701 of 1856 PMIDs
Fetched 711 of 1856 PMIDs
Fetched 721 of 1856 PMIDs
Fetched 731 of 1856 PMIDs
Fetched 741 of 1856 PMIDs
Fetched 751 of 1856 PMIDs
Fetched 761 of 1856 PMIDs
Fetched 771 of 1856 PMIDs
Fetched 781 of 1856 PMIDs
Fetched 791 of 1856 PMIDs
Fetched 801 of 1856 PMIDs
Fetched 811 of 1856 PMIDs
Fetched 821 of 1856 PMIDs
Fetched 831 of 1856 PMIDs
Fetched 841 of 1856 PMIDs
Fetched 851 of 1856 PMIDs
Fetched 861 of 1856 PMIDs
Fetched 871 of 1856 PMIDs
Fetched 881 of 1856 PMIDs
Fetched 891 of 1856 PMIDs
Fetched 901 of 1856 PMIDs
Fetched 911 of 1856 PMIDs
Fetched 921 of 1856 PMIDs
Fetched 931 of 1856 PMIDs
Fetched 941 of 1856 PMIDs
Fetched 951 of 1856 PMIDs
Fetched 961 of 1856 PMIDs
Fetched 971 of 1856 PMIDs
Fetched 981 of 1856 PMIDs
Fetched 991 of 1856 PMIDs
Fetched 1001 of 1856 PMIDs
Fetched 1011 of 1856 PMIDs
Fetched 1021 of 1856 PMIDs
Fetched 1031 of 1856 PMIDs
Fetched 1041 of 1856 PMIDs
Fetched 1051 of 1856 PMIDs
Fetched 1061 of 1856 PMIDs
Fetched 1071 of 1856 PMIDs
Fetched 1081 of 1856 PMIDs
Fetched 1091 of 1856 PMIDs
Fetched 1101 of 1856 PMIDs
Fetched 1111 of 1856 PMIDs
Fetched 1121 of 1856 PMIDs
Fetched 1131 of 1856 PMIDs
Fetched 1141 of 1856 PMIDs
Fetched 1151 of 1856 PMIDs
Fetched 1161 of 1856 PMIDs
Fetched 1171 of 1856 PMIDs
Fetched 1181 of 1856 PMIDs
Fetched 1191 of 1856 PMIDs
Fetched 1201 of 1856 PMIDs
Fetched 1211 of 1856 PMIDs
Fetched 1221 of 1856 PMIDs
Fetched 1231 of 1856 PMIDs
Fetched 1241 of 1856 PMIDs
Fetched 1251 of 1856 PMIDs
Fetched 1261 of 1856 PMIDs
Fetched 1271 of 1856 PMIDs
Fetched 1281 of 1856 PMIDs
Fetched 1291 of 1856 PMIDs
Fetched 1301 of 1856 PMIDs
Fetched 1311 of 1856 PMIDs
Fetched 1321 of 1856 PMIDs
Fetched 1331 of 1856 PMIDs
Fetched 1341 of 1856 PMIDs
Fetched 1351 of 1856 PMIDs
Fetched 1361 of 1856 PMIDs
Fetched 1371 of 1856 PMIDs
Fetched 1381 of 1856 PMIDs
Fetched 1391 of 1856 PMIDs
Fetched 1401 of 1856 PMIDs
Fetched 1411 of 1856 PMIDs
Fetched 1421 of 1856 PMIDs
Fetched 1431 of 1856 PMIDs
Fetched 1441 of 1856 PMIDs
Fetched 1451 of 1856 PMIDs
Fetched 1461 of 1856 PMIDs
Fetched 1471 of 1856 PMIDs
Fetched 1481 of 1856 PMIDs
Fetched 1491 of 1856 PMIDs
Fetched 1501 of 1856 PMIDs
Fetched 1511 of 1856 PMIDs
Fetched 1521 of 1856 PMIDs
Fetched 1531 of 1856 PMIDs
Fetched 1541 of 1856 PMIDs
Fetched 1551 of 1856 PMIDs
Fetched 1561 of 1856 PMIDs
Fetched 1571 of 1856 PMIDs
Fetched 1581 of 1856 PMIDs
Fetched 1591 of 1856 PMIDs
Fetched 1601 of 1856 PMIDs
Fetched 1611 of 1856 PMIDs
Fetched 1621 of 1856 PMIDs
Fetched 1631 of 1856 PMIDs
Fetched 1641 of 1856 PMIDs
Fetched 1651 of 1856 PMIDs
Fetched 1661 of 1856 PMIDs
Fetched 1671 of 1856 PMIDs
Fetched 1681 of 1856 PMIDs
Fetched 1691 of 1856 PMIDs
Fetched 1701 of 1856 PMIDs
Fetched 1711 of 1856 PMIDs
Fetched 1721 of 1856 PMIDs
Fetched 1731 of 1856 PMIDs
Fetched 1741 of 1856 PMIDs
Fetched 1751 of 1856 PMIDs
Fetched 1761 of 1856 PMIDs
Fetched 1771 of 1856 PMIDs
Fetched 1781 of 1856 PMIDs
Fetched 1791 of 1856 PMIDs
Fetched 1801 of 1856 PMIDs
Fetched 1811 of 1856 PMIDs
Fetched 1821 of 1856 PMIDs
Fetched 1831 of 1856 PMIDs
Fetched 1841 of 1856 PMIDs
Fetched 1851 of 1856 PMIDs

In [17]:
df.to_csv("AfricanAmerican_with_abstracts.csv", index=False)
print("Saved AfricanAmerican_with_abstracts.csv!")

Saved AfricanAmerican_with_abstracts.csv!

In [18]:
df[["PMID", "Abstract"]].head(5)

KeyError: "['Abstract'] not in index"

In [19]:
df.columns

Index(['PMID', 'Title', 'Authors', 'Citation', 'First Author', 'Journal/Book',
       'Publication Year', 'Create Date', 'PMCID', 'NIHMS ID', 'DOI'],
      dtype='object')

In [20]:
pmids = df["PMID"].dropna().astype(str).tolist()
print(pmids[:5])  # shows first 5 PMIDs

['41491560', '41402564', '41385717', '41283203', '41208612']

In [21]:
df["Abstract"] = ""  # empty column to store abstracts

In [22]:
from Bio import Entrez
import time

Entrez.email = "mrakkar@sas.upenn.edu"  # replace with your real email

def fetch_abstract(pmid):
    try:
        handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
        records = Entrez.read(handle)
        article = records["PubmedArticle"][0]
        abstract = article["MedlineCitation"]["Article"].get("Abstract", {})
        if "AbstractText" in abstract:
            return " ".join(abstract["AbstractText"])
        else:
            return ""
    except:
        return ""

for i, pmid in enumerate(pmids):
    df.at[i, "Abstract"] = fetch_abstract(pmid)
    if i % 10 == 0:
        print(f"Fetched {i+1} of {len(pmids)} PMIDs")
    time.sleep(0.3)  # avoid hitting PubMed rate limits

Fetched 1 of 1856 PMIDs
Fetched 11 of 1856 PMIDs
Fetched 21 of 1856 PMIDs
Fetched 31 of 1856 PMIDs
Fetched 41 of 1856 PMIDs
Fetched 51 of 1856 PMIDs
Fetched 61 of 1856 PMIDs
Fetched 71 of 1856 PMIDs
Fetched 81 of 1856 PMIDs
Fetched 91 of 1856 PMIDs
Fetched 101 of 1856 PMIDs
Fetched 111 of 1856 PMIDs
Fetched 121 of 1856 PMIDs
Fetched 131 of 1856 PMIDs
Fetched 141 of 1856 PMIDs
Fetched 151 of 1856 PMIDs
Fetched 161 of 1856 PMIDs
Fetched 171 of 1856 PMIDs
Fetched 181 of 1856 PMIDs
Fetched 191 of 1856 PMIDs
Fetched 201 of 1856 PMIDs
Fetched 211 of 1856 PMIDs
Fetched 221 of 1856 PMIDs
Fetched 231 of 1856 PMIDs
Fetched 241 of 1856 PMIDs
Fetched 251 of 1856 PMIDs
Fetched 261 of 1856 PMIDs
Fetched 271 of 1856 PMIDs
Fetched 281 of 1856 PMIDs
Fetched 291 of 1856 PMIDs
Fetched 301 of 1856 PMIDs
Fetched 311 of 1856 PMIDs
Fetched 321 of 1856 PMIDs

KeyboardInterrupt:

In [23]:
from Bio import Entrez
import time

# Replace with your actual email
Entrez.email = "mrakkar@sas.upenn.edu"

# Make sure your dataframe df exists and pmids list is ready
# df["Abstract"] should exist (empty column)
if "Abstract" not in df.columns:
    df["Abstract"] = ""

# Fetch abstracts with live progress and peek
for i, pmid in enumerate(pmids):
    df.at[i, "Abstract"] = fetch_abstract(pmid)
    
    # Show progress every 5 papers
    if (i+1) % 5 == 0 or i == 0:
        print(f"Fetched {i+1} of {len(pmids)} PMIDs")
        # Peek at the first abstract fetched so far
        first_filled = df[df["Abstract"].str.len() > 0].iloc[0]["Abstract"]
        print(f"First abstract fetched so far:\n{first_filled[:300]}...\n")  # show first 300 chars
    
    time.sleep(0.3)  # avoid PubMed rate limits

Fetched 1 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 5 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 10 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 15 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 20 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 25 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 30 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 35 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 40 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 45 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 50 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 55 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 60 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 65 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 70 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 75 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 80 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 85 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 90 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 95 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 100 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 105 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 110 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 115 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 120 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 125 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 130 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 135 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 140 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 145 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 150 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 155 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 160 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 165 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 170 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 175 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 180 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 185 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 190 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 195 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 200 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 205 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 210 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 215 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 220 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 225 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 230 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 235 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 240 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 245 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 250 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 255 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 260 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 265 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 270 of 1856 PMIDs
First abstract fetched so far:
Electronic health records and patient portals allow patients to communicate with physicians and other members of the health care team. However, few studies have investigated the impact of these tools on chronic disease management. This study examines how patient portal activity can influence the man...

Fetched 275 of 1856 PMIDs
First abstract fetched so far:

In [24]:
df.to_csv("AfricanAmerican_with_abstracts.csv", index=False)
print("Saved CSV with abstracts!")

Saved CSV with abstracts!

In [25]:
from Bio import Entrez
import pandas as pd
import time

# Replace with your email
Entrez.email = "mrakkar@sas.upenn.edu"

# ----------------------------
# Step 1: Load your CSV
# ----------------------------
# Replace filename for each dataset
csv_input = "csv-AsianAmeri-set.csv"
csv_output = "SouthAsian_with_abstracts.csv"

df = pd.read_csv(csv_input)

# Make sure PMID column exists (replace with exact name)
pmid_col = "PMID"  # or "pmid", check df.columns if unsure
pmids = df[pmid_col].dropna().astype(str).tolist()

# ----------------------------
# Step 2: Create Abstract column
# ----------------------------
if "Abstract" not in df.columns:
    df["Abstract"] = ""

# ----------------------------
# Step 3: Function to fetch abstracts
# ----------------------------
def fetch_abstract(pmid):
    try:
        handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
        records = Entrez.read(handle)
        article = records["PubmedArticle"][0]
        abstract = article["MedlineCitation"]["Article"].get("Abstract", {})
        if "AbstractText" in abstract:
            return " ".join(abstract["AbstractText"])
        else:
            return ""
    except:
        return ""

# ----------------------------
# Step 4: Fetch abstracts with progress
# ----------------------------
for i, pmid in enumerate(pmids):
    df.at[i, "Abstract"] = fetch_abstract(pmid)
    
    # Progress every 5 papers
    if (i+1) % 5 == 0 or i == 0:
        print(f"Fetched {i+1} of {len(pmids)} PMIDs")
        # Peek at the first abstract fetched so far
        filled = df[df["Abstract"].str.len() > 0]
        if not filled.empty:
            print(f"First abstract preview:\n{filled.iloc[0]['Abstract'][:300]}...\n")
    
    time.sleep(0.3)  # avoid hitting PubMed too fast

# ----------------------------
# Step 5: Save CSV with abstracts
# ----------------------------
df.to_csv(csv_output, index=False)
print(f"Saved {csv_output} with abstracts!")

Fetched 1 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 5 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 10 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 15 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 20 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 25 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 30 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 35 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 40 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 45 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 50 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 55 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Fetched 60 of 61 PMIDs
First abstract preview:
Remnant cholesterol (RC) may contribute to residual risk of atherosclerotic cardiovascular disease (ASCVD), but few studies have examined this in South Asian populations, who experience a disproportionately high incidence of ASCVD. Using data from the Mediators of Atherosclerosis in South Asians Liv...

Saved SouthAsian_with_abstracts.csv with abstracts!

In [26]:
from Bio import Entrez
import pandas as pd
import time

# Replace with your email
Entrez.email = "your_email@example.com"

# ----------------------------
# Step 1: Load your CSV
# ----------------------------
# Replace filename for each dataset
csv_input = "csv-AsianTitle-set.csv"
csv_output = "Asians_with_abstracts.csv"

df = pd.read_csv(csv_input)

# Make sure PMID column exists (replace with exact name)
pmid_col = "PMID"  # or "pmid", check df.columns if unsure
pmids = df[pmid_col].dropna().astype(str).tolist()

# ----------------------------
# Step 2: Create Abstract column
# ----------------------------
if "Abstract" not in df.columns:
    df["Abstract"] = ""

# ----------------------------
# Step 3: Function to fetch abstracts
# ----------------------------
def fetch_abstract(pmid):
    try:
        handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
        records = Entrez.read(handle)
        article = records["PubmedArticle"][0]
        abstract = article["MedlineCitation"]["Article"].get("Abstract", {})
        if "AbstractText" in abstract:
            return " ".join(abstract["AbstractText"])
        else:
            return ""
    except:
        return ""

# ----------------------------
# Step 4: Fetch abstracts with progress
# ----------------------------
for i, pmid in enumerate(pmids):
    df.at[i, "Abstract"] = fetch_abstract(pmid)
    
    # Progress every 5 papers
    if (i+1) % 5 == 0 or i == 0:
        print(f"Fetched {i+1} of {len(pmids)} PMIDs")
        # Peek at the first abstract fetched so far
        filled = df[df["Abstract"].str.len() > 0]
        if not filled.empty:
            print(f"First abstract preview:\n{filled.iloc[0]['Abstract'][:300]}...\n")
    
    time.sleep(0.3)  # avoid hitting PubMed too fast

# ----------------------------
# Step 5: Save CSV with abstracts
# ----------------------------
df.to_csv(csv_output, index=False)
print(f"Saved {csv_output} with abstracts!")

Fetched 1 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 5 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 10 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 15 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 20 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 25 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 30 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 35 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 40 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 45 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 50 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 55 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 60 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 65 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 70 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 75 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 80 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 85 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 90 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 95 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 100 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 105 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 110 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 115 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 120 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 125 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 130 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 135 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 140 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 145 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 150 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 155 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 160 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 165 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 170 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 175 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 180 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 185 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 190 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 195 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 200 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 205 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 210 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 215 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 220 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 225 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 230 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 235 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 240 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 245 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 250 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 255 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 260 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 265 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 270 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 275 of 4621 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 280 of 4621 PMIDs
First abstract preview:

KeyboardInterrupt:

In [ ]:
df.to_csv("Asian_with_abstracts_partial.csv", index=False)
print("Saved partial CSV with abstracts so far!")

In [ ]:
df.to_csv("Asian_with_abstracts_partial.csv", index=False)
print("Saved partial CSV with abstracts so far!")

In [27]:
df.to_csv("Asian_with_abstracts_partial.csv", index=False)
print("Saved partial CSV with abstracts so far!")

Saved partial CSV with abstracts so far!

In [28]:
df = pd.read_csv("Asian_with_abstracts_partial.csv")

In [29]:
# Find indexes of rows without abstracts
remaining = df[df["Abstract"].isna() | (df["Abstract"].str.len() == 0)]
print(f"{len(remaining)} PMIDs left to fetch")

4076 PMIDs left to fetch

In [30]:
pmids_remaining = remaining["PMID"].astype(str).tolist()

In [31]:
for i, pmid in enumerate(pmids_remaining):
    # Get the original index in df
    idx = remaining.index[i]
    df.at[idx, "Abstract"] = fetch_abstract(pmid)
    
    if (i+1) % 10 == 0 or i == 0:
        print(f"Fetched {i+1} of {len(pmids_remaining)} remaining PMIDs")
        filled = df[df["Abstract"].str.len() > 0]
        if not filled.empty:
            print(f"First abstract preview:\n{filled.iloc[0]['Abstract'][:300]}...\n")
    
    time.sleep(0.3)

Fetched 1 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 10 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 20 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 30 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 40 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 50 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 60 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 70 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 80 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 90 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 100 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 110 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 120 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 130 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 140 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 150 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 160 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 170 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 180 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 190 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 200 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 210 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 220 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 230 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 240 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 250 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 260 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 270 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 280 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 290 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 300 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 310 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 320 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 330 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 340 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 350 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 360 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 370 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 380 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 390 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 400 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 410 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 420 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 430 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 440 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 450 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 460 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 470 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 480 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 490 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 500 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 510 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 520 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 530 of 4076 remaining PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 540 of 4076 remaining PMIDs
First abstract preview:

In [32]:
df.to_csv("Asians_with_abstracts_final.csv", index=False)
print("Saved final CSV with all abstracts!")

Saved final CSV with all abstracts!

In [1]:
from Bio import Entrez
import pandas as pd
import time

# Replace with your email
Entrez.email = "mrakkar@sas.upenn.edu"

# ----------------------------
# Step 1: Load your CSV
# ----------------------------
# Replace filename for each dataset
csv_input = "csv-SouthAsian-set.csv"
csv_output = "SouthAsian_with_abstracts.csv"

df = pd.read_csv(csv_input)

# Make sure PMID column exists (replace with exact name)
pmid_col = "PMID"  # or "pmid", check df.columns if unsure
pmids = df[pmid_col].dropna().astype(str).tolist()

# ----------------------------
# Step 2: Create Abstract column
# ----------------------------
if "Abstract" not in df.columns:
    df["Abstract"] = ""

# ----------------------------
# Step 3: Function to fetch abstracts
# ----------------------------
def fetch_abstract(pmid):
    try:
        handle = Entrez.efetch(db="pubmed", id=pmid, retmode="xml")
        records = Entrez.read(handle)
        article = records["PubmedArticle"][0]
        abstract = article["MedlineCitation"]["Article"].get("Abstract", {})
        if "AbstractText" in abstract:
            return " ".join(abstract["AbstractText"])
        else:
            return ""
    except:
        return ""

# ----------------------------
# Step 4: Fetch abstracts with progress
# ----------------------------
for i, pmid in enumerate(pmids):
    df.at[i, "Abstract"] = fetch_abstract(pmid)
    
    # Progress every 5 papers
    if (i+1) % 5 == 0 or i == 0:
        print(f"Fetched {i+1} of {len(pmids)} PMIDs")
        # Peek at the first abstract fetched so far
        filled = df[df["Abstract"].str.len() > 0]
        if not filled.empty:
            print(f"First abstract preview:\n{filled.iloc[0]['Abstract'][:300]}...\n")
    
    time.sleep(0.3)  # avoid hitting PubMed too fast

# ----------------------------
# Step 5: Save CSV with abstracts
# ----------------------------
df.to_csv(csv_output, index=False)
print(f"Saved {csv_output} with abstracts!")

Fetched 1 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 5 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 10 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 15 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 20 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 25 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 30 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 35 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 40 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 45 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 50 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 55 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 60 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 65 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 70 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 75 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 80 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 85 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 90 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 95 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 100 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 105 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 110 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 115 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 120 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 125 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 130 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 135 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 140 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 145 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 150 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 155 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 160 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 165 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 170 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 175 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 180 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 185 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 190 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 195 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 200 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 205 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 210 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 215 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 220 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 225 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 230 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 235 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 240 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 245 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 250 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 255 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 260 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 265 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 270 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 275 of 371 PMIDs
First abstract preview:
Background & objectives Little data exist on population-based incidence of diabetes related complications in developing countries. We assessed sex-specific incidence of complications among Asian Indians with type 2 diabetes (T2D) based on follow up assessments from a community-based cohort. Methods ...

Fetched 280 of 371 PMIDs
First abstract preview:

In [4]:
import pandas as pd

df1 = pd.read_csv("AfricanAmerican_with_abstracts.csv")
df2 = pd.read_csv("SouthAsian_with_abstracts.csv")
df3 = pd.read_csv("Asians_with_abstracts_final.csv")
df4 = pd.read_csv("asianameri_with_abstracts.csv")

df = pd.concat([df1, df2, df3, df4], ignore_index=True)

df.head()

,PMID,Title,Authors,Citation,First Author,Journal/Book,Publication Year,Create Date,PMCID,NIHMS ID,DOI,Abstract
0,41491560,Patient Portal Frequency of Use in Patients wi...,"Anderi E, Eisman EB, Bryant A, Hunt T, Mahal M...",J Am Board Fam Med. 2025 Sep-Oct;38(5):868-876...,Anderi E,J Am Board Fam Med,2025,2026/01/06,PMC12978604,NaN,10.3122/jabfm.2025.250069R1,Electronic health records and patient portals ...
1,41402564,Trends in Dementia Associated Mortality among ...,"Hassan ST, Onaiz SL, Meghwar S, Ahmed FK, Hyde...",J Epidemiol Glob Health. 2025 Dec 17;15(1):147...,Hassan ST,J Epidemiol Glob Health,2025,2025/12/16,PMC12715058,NaN,10.1007/s44197-025-00500-z,Dementia contributes significantly to morbidit...
2,41385717,Sociotechnical Needs of Registered Nurses in t...,"Williams TB, Bimali M, Garza MY, Parker P, Pal...",JMIR Nurs. 2025 Dec 12;8:e75080. doi: 10.2196/...,Williams TB,JMIR Nurs,2025,2025/12/12,PMC12700336,NaN,10.2196/75080,The African American population is disproporti...
3,41283203,Burden of Unfair Treatment and Subclinical Ath...,"Ashe JJ, Cuevas AG, Skipper AD, Bentley-Edward...",J Am Heart Assoc. 2025 Dec 2;14(23):e043832. d...,Ashe JJ,J Am Heart Assoc,2025,2025/11/24,PMC12748514,NaN,10.1161/JAHA.125.043832,This study examined whether religious coping m...
4,41208612,Retrospective cohort analysis of low-molecular...,"Chang CY, Hsu CP, Cheng CT, Chen DY, Hsieh MJ,...",Int J Surg. 2026 Feb 1;112(2):4111-4119. doi: ...,Chang CY,Int J Surg,2026,2025/11/10,NaN,NaN,10.1097/JS9.0000000000003882,Venous thromboembolism (VTE) is a significant ...

In [5]:
df["Abstract"] = df["Abstract"].fillna("").astype(str).str.lower()

In [6]:
import re

# ----------------------------
# KEYWORD LISTS
# ----------------------------
human_terms = ["participants", "patients", "adults", "children", "cohort", "subjects"]

# ----------------------------
# CVD TERMS
# ----------------------------
cvd_terms = [
    # General
    "cardiovascular disease", "cardiovascular diseases", "cvd",
    "heart disease", "heart diseases", "cardiac disease", "cardiac diseases",

    # Coronary / ischemic
    "coronary artery disease", "cad", "ischemic heart disease", "ihd",
    "myocardial infarction", "heart attack",
    "acute coronary syndrome", "acs", "angina",

    # Heart failure
    "heart failure", "congestive heart failure", "chf",
    "cardiomyopathy",

    # Cerebrovascular
    "stroke", "cerebrovascular disease", "cerebrovascular diseases",
    "cerebrovascular accident", "cva",
    "ischemic stroke", "hemorrhagic stroke",
    "transient ischemic attack", "tia",

    # Arrhythmias
    "arrhythmia", "atrial fibrillation", "afib",
    "ventricular tachycardia", "ventricular fibrillation",

    # Vascular
    "atherosclerosis", "arteriosclerosis",
    "peripheral artery disease", "pad",
    "vascular disease", "thrombosis", "embolism",

    # Risk factors
    "hypertension", "high blood pressure",
    "hyperlipidemia", "dyslipidemia", "cholesterol"
]

# ----------------------------
# RACE / ETHNICITY TERMS
# ----------------------------
black_terms = ["black", "african american"]

south_asian_terms = [
    "south asian", "indian", "pakistani", "bangladeshi", "sri lankan",
    "nepalese", "bhutanese", "desi"
]

# Broad Asian category
asian_agg_terms = ["asian", "asian american", "asian americans"]

# ANY Asian subgroup = disaggregation (expanded to include less common)
disagg_terms = [
    "indian", "pakistani", "bangladeshi", "sri lankan", "nepalese", "bhutanese",
    "chinese", "japanese", "korean", "vietnamese", "filipino", "thai",
    "malaysian", "singaporean", "indonesian", "cambodian", "laotian", "burmese"
]

# ----------------------------
# FUNCTIONS
# ----------------------------

# Case-insensitive + word boundaries for short abbreviations
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()
    for term in terms:
        if term in ["cad", "acs", "chf", "cva", "tia", "afib", "pad", "ihd", "cvd"]:
            if re.search(rf"\b{term}\b", text):
                return True
        else:
            if term in text:
                return True
    return False

# Fixed US detection
def check_us(text):
    if not isinstance(text, str):
        return False
    return (
        "united states" in text.lower() or
        "usa" in text.lower() or
        "u.s." in text.lower() or
        re.search(r"\bUS\b", text, re.IGNORECASE) is not None or
        "american" in text.lower()
    )

# ----------------------------
# APPLY CODING
# ----------------------------
df["US_based"] = df["Abstract"].apply(check_us)

df["Human_subjects"] = df["Abstract"].apply(lambda x: check_terms(x, human_terms))
df["CVD_flag"] = df["Abstract"].apply(lambda x: check_terms(x, cvd_terms))
df["Black_mentions"] = df["Abstract"].apply(lambda x: check_terms(x, black_terms))
df["South_Asian_mentions"] = df["Abstract"].apply(lambda x: check_terms(x, south_asian_terms))
df["Asian_aggregation"] = df["Abstract"].apply(lambda x: check_terms(x, asian_agg_terms))
df["Disaggregation"] = df["Abstract"].apply(lambda x: check_terms(x, disagg_terms))

# ----------------------------
# SAVE
# ----------------------------
df.to_csv("coded_abstracts.csv", index=False)
print("✅ Done! Saved as coded_abstracts.csv")

✅ Done! Saved as coded_abstracts.csv

In [4]:
import pandas as pd
import re

def parse_pubmed_file(filename):
    records = []
    current_record = {"Abstract": "", "Affiliations": ""}

    with open(filename, "r") as file:
        for line in file:
            line = line.strip()
            
            if line.startswith("PMID-"):
                if current_record["Abstract"] or current_record["Affiliations"]:
                    records.append(current_record)
                current_record = {"Abstract": "", "Affiliations": ""}
            
            elif line.startswith("AB  -"):
                current_record["Abstract"] += line.replace("AB  -", "").strip() + " "
            
            elif line.startswith("AD  -"):
                current_record["Affiliations"] += line.replace("AD  -", "").strip() + " "
        
        records.append(current_record)

    return pd.DataFrame(records)

In [5]:
df1_pubmed = parse_pubmed_file("group1.txt")
df2_pubmed = parse_pubmed_file("group2.txt")
df3_pubmed = parse_pubmed_file("group3.txt")
df4_pubmed = parse_pubmed_file("group4.txt")

In [6]:
df_pubmed = pd.concat(
    [df1_pubmed, df2_pubmed, df4_pubmed, df3_pubmed],
    ignore_index=True
)

In [7]:
len(df)
len(df_pubmed)

NameError: name 'df' is not defined

In [8]:
import pandas as pd

df = pd.read_csv("coded_abstracts.csv")

In [9]:
print(df.shape)   # Shows number of rows and columns
print(df.columns) # Shows the column names
print(df.head())  # First few rows

(6909, 19)
Index(['PMID', 'Title', 'Authors', 'Citation', 'First Author', 'Journal/Book',
       'Publication Year', 'Create Date', 'PMCID', 'NIHMS ID', 'DOI',
       'Abstract', 'US_based', 'Human_subjects', 'CVD_flag', 'Black_mentions',
       'South_Asian_mentions', 'Asian_aggregation', 'Disaggregation'],
      dtype='object')
       PMID                                              Title  \
0  41491560  Patient Portal Frequency of Use in Patients wi...
1  41402564  Trends in Dementia Associated Mortality among ...
2  41385717  Sociotechnical Needs of Registered Nurses in t...
3  41283203  Burden of Unfair Treatment and Subclinical Ath...
4  41208612  Retrospective cohort analysis of low-molecular...

                                             Authors  \
0  Anderi E, Eisman EB, Bryant A, Hunt T, Mahal M...
1  Hassan ST, Onaiz SL, Meghwar S, Ahmed FK, Hyde...
2  Williams TB, Bimali M, Garza MY, Parker P, Pal...
3  Ashe JJ, Cuevas AG, Skipper AD, Bentley-Edward...
4  Chang CY, Hsu CP, Cheng CT, Chen DY, Hsieh MJ,...

                                            Citation First Author  \
0  J Am Board Fam Med. 2025 Sep-Oct;38(5):868-876...     Anderi E
1  J Epidemiol Glob Health. 2025 Dec 17;15(1):147...    Hassan ST
2  JMIR Nurs. 2025 Dec 12;8:e75080. doi: 10.2196/...  Williams TB
3  J Am Heart Assoc. 2025 Dec 2;14(23):e043832. d...      Ashe JJ
4  Int J Surg. 2026 Feb 1;112(2):4111-4119. doi: ...     Chang CY

              Journal/Book  Publication Year Create Date        PMCID  \
0       J Am Board Fam Med              2025  2026/01/06  PMC12978604
1  J Epidemiol Glob Health              2025  2025/12/16  PMC12715058
2                JMIR Nurs              2025  2025/12/12  PMC12700336
3         J Am Heart Assoc              2025  2025/11/24  PMC12748514
4               Int J Surg              2026  2025/11/10          NaN

  NIHMS ID                           DOI  \
0      NaN   10.3122/jabfm.2025.250069R1
1      NaN    10.1007/s44197-025-00500-z
2      NaN                 10.2196/75080
3      NaN       10.1161/JAHA.125.043832
4      NaN  10.1097/JS9.0000000000003882

                                            Abstract  US_based  \
0  electronic health records and patient portals ...      True
1  dementia contributes significantly to morbidit...      True
2  the african american population is disproporti...      True
3  this study examined whether religious coping m...     False
4  venous thromboembolism (vte) is a significant ...      True

   Human_subjects  CVD_flag  Black_mentions  South_Asian_mentions  \
0            True      True            True                 False
1            True      True            True                 False
2            True      True            True                  True
3            True      True            True                 False
4            True      True            True                 False

   Asian_aggregation  Disaggregation
0              False           False
1              False           False
2               True           False
3              False           False
4               True           False

In [10]:
df1_pubmed = parse_pubmed_file("group1.txt")
df2_pubmed = parse_pubmed_file("group2.txt")
df3_pubmed = parse_pubmed_file("group3.txt")
df4_pubmed = parse_pubmed_file("group4.txt")

In [11]:
df_pubmed = pd.concat([df1_pubmed, df2_pubmed, df4_pubmed, df3_pubmed], ignore_index=True)

In [12]:
print(len(df))
print(len(df_pubmed))

6909
6893

In [14]:
import pandas as pd

df = pd.read_csv("coded_abstracts.csv")
print(df.columns)

Index(['PMID', 'Title', 'Authors', 'Citation', 'First Author', 'Journal/Book',
       'Publication Year', 'Create Date', 'PMCID', 'NIHMS ID', 'DOI',
       'Abstract', 'US_based', 'Human_subjects', 'CVD_flag', 'Black_mentions',
       'South_Asian_mentions', 'Asian_aggregation', 'Disaggregation'],
      dtype='object')

In [15]:
import re
import pandas as pd

def parse_pubmed_file_with_pmid(filename):
    records = []
    current_record = {"PMID": "", "Abstract": "", "Affiliations": ""}

    with open(filename, "r") as file:
        for line in file:
            line = line.strip()
            
            # New record starts with PMID
            if line.startswith("PMID-"):
                if current_record["PMID"]:
                    records.append(current_record)
                current_record = {"PMID": "", "Abstract": "", "Affiliations": ""}
                current_record["PMID"] = line.replace("PMID-", "").strip()
            
            elif line.startswith("AB  -"):
                current_record["Abstract"] += line.replace("AB  -", "").strip() + " "
            
            elif line.startswith("AD  -"):
                current_record["Affiliations"] += line.replace("AD  -", "").strip() + " "

    # Add last record
    records.append(current_record)
    return pd.DataFrame(records)

In [16]:
df1_pubmed = parse_pubmed_file_with_pmid("group1.txt")
df2_pubmed = parse_pubmed_file_with_pmid("group2.txt")
df3_pubmed = parse_pubmed_file_with_pmid("group3.txt")
df4_pubmed = parse_pubmed_file_with_pmid("group4.txt")

In [17]:
df_pubmed = pd.concat([df1_pubmed, df2_pubmed, df4_pubmed, df3_pubmed], ignore_index=True)

In [18]:
print(df_pubmed["PMID"].duplicated().sum())  # Should be 0 ideally
print(df_pubmed.shape)

400
(6910, 3)

In [19]:
# Combine duplicate PMIDs by joining affiliations
df_pubmed_unique = df_pubmed.groupby("PMID").agg({
    "Abstract": "first",  # take first abstract (all same for a PMID)
    "Affiliations": lambda x: " ; ".join(filter(None, x))  # combine all affiliations
}).reset_index()

In [20]:
print(df_pubmed_unique.shape)
print(df_pubmed_unique["PMID"].duplicated().sum())  # should be 0

(6510, 3)
0

In [21]:
df = df.merge(
    df_pubmed_unique[["PMID", "Affiliations"]],
    on="PMID",
    how="left"
)

ValueError: You are trying to merge on int64 and object columns for key 'PMID'. If you wish to proceed you should use pd.concat

In [22]:
# Convert master df PMID to string
df["PMID"] = df["PMID"].astype(str)

# Convert parsed df PMID to string
df_pubmed_unique["PMID"] = df_pubmed_unique["PMID"].astype(str)

In [23]:
df = df.merge(
    df_pubmed_unique[["PMID", "Affiliations"]],
    on="PMID",
    how="left"
)

In [24]:
print(df.shape)          # should still be 6909 rows
print(df["Affiliations"].isna().sum())  # number of abstracts without affiliations

(6909, 20)
0

In [25]:
def check_us_combined(abstract, affiliation):
    text = ""
    if isinstance(abstract, str):
        text += abstract.lower() + " "
    if isinstance(affiliation, str):
        text += affiliation.lower()
    
    return (
        "united states" in text or
        "usa" in text or
        "u.s." in text or
        re.search(r"\bUS\b", text, re.IGNORECASE) is not None or
        "american" in text
    )

df["US_based"] = df.apply(
    lambda row: check_us_combined(row["Abstract"], row["Affiliations"]),
    axis=1
)

In [26]:
us_states = [
    "alabama","al","alaska","ak","arizona","az","arkansas","ar",
    "california","ca","colorado","co","connecticut","ct","delaware","de",
    "florida","fl","georgia","ga","hawaii","hi","idaho","id","illinois","il",
    "indiana","in","iowa","ia","kansas","ks","kentucky","ky","louisiana","la",
    "maine","me","maryland","md","massachusetts","ma","michigan","mi","minnesota","mn",
    "mississippi","ms","missouri","mo","montana","mt","nebraska","ne","nevada","nv",
    "new hampshire","nh","new jersey","nj","new mexico","nm","new york","ny","north carolina","nc",
    "north dakota","nd","ohio","oh","oklahoma","ok","oregon","or","pennsylvania","pa",
    "rhode island","ri","south carolina","sc","south dakota","sd","tennessee","tn","texas","tx",
    "utah","ut","vermont","vt","virginia","va","washington","wa","west virginia","wv",
    "wisconsin","wi","wyoming","wy","district of columbia","dc"
]

In [27]:
import re

def check_us_enhanced(abstract, affiliation):
    text = ""
    if isinstance(abstract, str):
        text += abstract.lower() + " "
    if isinstance(affiliation, str):
        text += affiliation.lower()
    
    # Explicit US terms
    if ("united states" in text or "usa" in text or "u.s." in text or 
        re.search(r"\bUS\b", text, re.IGNORECASE) or "american" in text):
        return True
    
    # Check for US state names or abbreviations
    for state in us_states:
        if state in text:
            return True
    
    return False

In [28]:
df["US_based"] = df.apply(
    lambda row: check_us_enhanced(row["Abstract"], row["Affiliations"]),
    axis=1
)

In [29]:
print(df["US_based"].value_counts())

US_based
True     6892
False      17
Name: count, dtype: int64

In [30]:
# Extract rows where US_based is False
false_us_rows = df[df["US_based"] == False]

# Optionally, save to CSV to check manually
false_us_rows.to_csv("US_false_to_check.csv", index=False)

In [31]:
# Add more if needed
non_research_keywords = [
    "letter to the editor",
    "letter",
    "editorial",
    "commentary",
    "correspondence"
]

In [32]:
def is_non_research(title):
    if not isinstance(title, str):
        return False
    title_lower = title.lower()
    return any(keyword in title_lower for keyword in non_research_keywords)

In [33]:
df["Non_research_article"] = df["Title"].apply(is_non_research)

In [34]:
df.loc[df["Non_research_article"] == True, "US_based"] = False

In [35]:
df[df["Non_research_article"] == True][["PMID","Title","US_based"]]

          PMID                                              Title  US_based
133   35440524  Letter to the Editor on "African Americans and...     False
420   29404946  Capsule Commentary on Murray et al. Antihypert...     False
436   29229625  Letter by Triantafyllou and Straub Regarding A...     False
3431  35100018  Letter by Enas and Varkey Regarding Article, "...     False
3432  35100017  Response by Patel and Khera to Letter Regardin...     False
4213  31280834  Letter to the Editor Regarding "Ticagrelor for...     False

In [36]:
df.to_csv("master_combined_US_final_flagged.csv", index=False)

In [37]:
import pandas as pd

# Reload your original master CSV
df = pd.read_csv("coded_abstracts.csv")

In [38]:
import pandas as pd
import re

# Load your current master CSV
df = pd.read_csv("coded_abstracts.csv")

# Make sure PMIDs are strings
df["PMID"] = df["PMID"].astype(str)

In [39]:
# Flag rows where Abstract is missing or empty
df["No_Abstract"] = df["Abstract"].isna() | (df["Abstract"].str.strip() == "")

In [40]:
# Default: include all
df["Include_in_analysis"] = True

# Mark rows with no abstract as False (they will be manually verified later)
df.loc[df["No_Abstract"] == True, "Include_in_analysis"] = False

In [41]:
non_research_keywords = [
    "letter to the editor", "letter", "editorial", "commentary", "correspondence"
]

def is_non_research(title):
    if not isinstance(title, str):
        return False
    title_lower = title.lower()
    return any(keyword in title_lower for keyword in non_research_keywords)

# Create a helper column
df["Non_research_article"] = df["Title"].apply(is_non_research)

# Set Include_in_analysis = False for non-research articles
df.loc[df["Non_research_article"] == True, "Include_in_analysis"] = False

In [42]:
# US states + abbreviations
us_states = [
    "alabama","al","alaska","ak","arizona","az","arkansas","ar",
    "california","ca","colorado","co","connecticut","ct","delaware","de",
    "florida","fl","georgia","ga","hawaii","hi","idaho","id","illinois","il",
    "indiana","in","iowa","ia","kansas","ks","kentucky","ky","louisiana","la",
    "maine","me","maryland","md","massachusetts","ma","michigan","mi","minnesota","mn",
    "mississippi","ms","missouri","mo","montana","mt","nebraska","ne","nevada","nv",
    "new hampshire","nh","new jersey","nj","new mexico","nm","new york","ny","north carolina","nc",
    "north dakota","nd","ohio","oh","oklahoma","ok","oregon","or","pennsylvania","pa",
    "rhode island","ri","south carolina","sc","south dakota","sd","tennessee","tn","texas","tx",
    "utah","ut","vermont","vt","virginia","va","washington","wa","west virginia","wv",
    "wisconsin","wi","wyoming","wy","district of columbia","dc"
]

def check_us_enhanced(abstract, affiliation):
    text = ""
    if isinstance(abstract, str):
        text += abstract.lower() + " "
    if isinstance(affiliation, str):
        text += affiliation.lower()
    
    # Explicit US terms
    if ("united states" in text or "usa" in text or "u.s." in text or 
        re.search(r"\bUS\b", text, re.IGNORECASE) or "american" in text):
        return True
    
    # Check for US state names or abbreviations
    for state in us_states:
        if state in text:
            return True
    
    return False

# Apply to master dataframe
df["US_based"] = df.apply(lambda row: check_us_enhanced(row["Abstract"], row.get("Affiliations","")), axis=1)

In [43]:
df.to_csv("master_combined_step1.csv", index=False)

In [45]:
import pandas as pd

df = pd.read_csv("master_combined_step1.csv")

In [46]:
human_terms = ["participants", "patients", "adults", "children", "cohort", "subjects"]

cvd_terms = [
    "cardiovascular disease","cardiovascular diseases","cvd",
    "heart disease","heart diseases","cardiac disease","cardiac diseases",
    "coronary artery disease","cad","ischemic heart disease","ihd",
    "myocardial infarction","heart attack","acute coronary syndrome","acs",
    "angina","heart failure","congestive heart failure","chf",
    "cardiomyopathy","stroke","cerebrovascular disease","cerebrovascular accident",
    "cva","ischemic stroke","hemorrhagic stroke","transient ischemic attack","tia",
    "arrhythmia","atrial fibrillation","afib","ventricular tachycardia","ventricular fibrillation",
    "atherosclerosis","arteriosclerosis","peripheral artery disease","pad",
    "vascular disease","thrombosis","embolism",
    "hypertension","high blood pressure",
    "hyperlipidemia","dyslipidemia","cholesterol"
]

black_terms = ["black", "african american"]

south_asian_terms = [
    "south asian","indian","pakistani","bangladeshi","sri lankan",
    "nepali","bhutanese","maldivian","desi"
]

asian_agg_terms = ["asian", "asian american", "asian americans"]

disagg_terms = [
    "indian","pakistani","bangladeshi","sri lankan",
    "chinese","japanese","korean","vietnamese",
    "filipino","thai","nepali","bhutanese","maldivian",
    "indonesian","malaysian","mongolian","taiwanese",
    "cambodian","laotian","hmong"
]

In [47]:
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()
    return any(term in text for term in terms)

In [48]:
df["Human_subjects"] = df["Abstract"].apply(lambda x: check_terms(x, human_terms))

df["CVD_flag"] = df["Abstract"].apply(lambda x: check_terms(x, cvd_terms))

df["Black_mentions"] = df["Abstract"].apply(lambda x: check_terms(x, black_terms))

df["South_Asian_mentions"] = df["Abstract"].apply(lambda x: check_terms(x, south_asian_terms))

df["Asian_aggregation"] = df["Abstract"].apply(lambda x: check_terms(x, asian_agg_terms))

df["Disaggregation"] = df["Abstract"].apply(lambda x: check_terms(x, disagg_terms))

In [49]:
df_final = df[df["Include_in_analysis"] == True]

In [50]:
print(df_final.shape)

print(df_final["CVD_flag"].value_counts())
print(df_final["Black_mentions"].value_counts())
print(df_final["South_Asian_mentions"].value_counts())

(6842, 22)
CVD_flag
True     6052
False     790
Name: count, dtype: int64
Black_mentions
False    4550
True     2292
Name: count, dtype: int64
South_Asian_mentions
False    5132
True     1710
Name: count, dtype: int64

In [51]:
df.to_csv("master_with_coding.csv", index=False)
df_final.to_csv("final_analysis_dataset.csv", index=False)

In [52]:
print(df.shape)

(6909, 22)

In [53]:
df["Abstract"].isna().sum()

np.int64(67)

In [54]:
import pandas as pd

# Load your cleaned master dataset
df = pd.read_csv("master_with_coding.csv")

In [55]:
print(df.columns)
print(df.shape)
print(df["Include_in_analysis"].value_counts())
print(df["US_based"].value_counts())
print(df["Human_subjects"].value_counts())
print(df["CVD_flag"].value_counts())

Index(['PMID', 'Title', 'Authors', 'Citation', 'First Author', 'Journal/Book',
       'Publication Year', 'Create Date', 'PMCID', 'NIHMS ID', 'DOI',
       'Abstract', 'US_based', 'Human_subjects', 'CVD_flag', 'Black_mentions',
       'South_Asian_mentions', 'Asian_aggregation', 'Disaggregation',
       'No_Abstract', 'Include_in_analysis', 'Non_research_article'],
      dtype='object')
(6909, 22)
Include_in_analysis
True     6842
False      67
Name: count, dtype: int64
US_based
True     6842
False      67
Name: count, dtype: int64
Human_subjects
True     6090
False     819
Name: count, dtype: int64
CVD_flag
True     6052
False     857
Name: count, dtype: int64

In [56]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &  # Has abstract + is research
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [57]:
df_analysis = df[df["Final_inclusion"] == True]

In [58]:
print("Total papers in master:", df.shape[0])
print("Papers included in analysis:", df_analysis.shape[0])

# Optional: check all flags in final dataset
print(df_analysis["US_based"].value_counts())        # should be all True
print(df_analysis["Human_subjects"].value_counts())  # should be all True
print(df_analysis["CVD_flag"].value_counts())        # should be all True

Total papers in master: 6909
Papers included in analysis: 5395
US_based
True    5395
Name: count, dtype: int64
Human_subjects
True    5395
Name: count, dtype: int64
CVD_flag
True    5395
Name: count, dtype: int64

In [59]:
# Keep full master with all flags for record-keeping
df.to_csv("master_with_final_inclusion.csv", index=False)

# Save the analysis dataset for your results
df_analysis.to_csv("final_analysis_dataset.csv", index=False)

In [60]:
import pandas as pd

# Load your latest master dataset
df = pd.read_csv("master_with_final_inclusion.csv")

In [61]:
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()  # lowercase everything
    return any(term in text for term in terms)

In [62]:
human_terms = [
    "participant", "participants",
    "patient", "patients",
    "adult", "adults",
    "child", "children",
    "cohort", "subjects",
    "individual", "individuals",
    "volunteer", "volunteers",
    "case", "cases",
    "people", "population",
    "african american", "african americans",
    "black",
    "south asian", "indian", "pakistani", "bangladeshi", "sri lankan",
    "chinese", "japanese", "korean", "vietnamese", "filipino", "thai",
    "elderly", "older adults"
]

In [63]:
df["Human_subjects"] = df["Abstract"].apply(lambda x: check_terms(x, human_terms))

In [64]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [65]:
# Filter abstracts where Human_subjects is False
human_false = df[df["Human_subjects"] == False]

In [66]:
print("Number of abstracts not flagged as human:", human_false.shape[0])

Number of abstracts not flagged as human: 110

In [67]:
print(human_false["PMID"].tolist())

[39216076, 35440524, 33957237, 32434217, 31158470, 30068700, 29909058, 29891236, 29404946, 29229625, 28619983, 26814167, 26117401, 25187575, 23095721, 20857770, 19398501, 17401394, 17092348, 17004422, 16469364, 15720042, 15253334, 15249517, 14969633, 11674903, 10532515, 10482169, 9688029, 9414897, 9414879, 9349915, 21289648, 15942456, 15711767, 40670315, 39531256, 38324147, 38270841, 38270840, 38184444, 38008348, 37162067, 36469595, 36259573, 35781275, 35100018, 35100017, 34560118, 33737330, 33436072, 33340436, 33239696, 33078954, 32858543, 31975319, 31950398, 31779799, 31280834, 31273340, 31032714, 30747852, 30691376, 30177043, 30031489, 30019069, 29962360, 29885691, 29679092, 29433473, 29417316, 29169577, 28884497, 28741654, 28485463, 28418750, 27965316, 27841857, 27452204, 27452203, 26580337, 26005168, 25441251, 24820752, 24775827, 24657882, 24162320, 23871617, 23871336, 23782730, 23770164, 23692491, 23465238, 23430079, 23344910, 21381596, 21044979, 19202994, 19201612, 18754019, 16306999, 15942456, 15619403, 15159226, 12061285, 12011204, 10418318, 10375045, 1389712, 34560118]

In [68]:
# Only rows with an abstract
human_false_with_abstract = df[(df["Human_subjects"] == False) & (df["No_Abstract"] == False)]

In [69]:
print("Number of abstracts with text not flagged as human:", human_false_with_abstract.shape[0])

Number of abstracts with text not flagged as human: 43

In [70]:
print(human_false_with_abstract["PMID"].tolist())

[39216076, 26117401, 25187575, 23095721, 20857770, 19398501, 17092348, 17004422, 14969633, 10532515, 10482169, 9349915, 15942456, 40670315, 39531256, 38324147, 37162067, 35781275, 33737330, 33436072, 33340436, 33239696, 32858543, 31950398, 30747852, 30177043, 29962360, 29433473, 29417316, 29169577, 28741654, 28418750, 27965316, 25441251, 24657882, 24162320, 23344910, 19202994, 15942456, 15619403, 15159226, 12061285, 1389712]

In [71]:
# Existing human terms (including previous population descriptors)
human_terms = [
    "participant", "participants",
    "patient", "patients",
    "adult", "adults",
    "child", "children",
    "cohort", "subjects",
    "individual", "individuals",
    "volunteer", "volunteers",
    "case", "cases",
    "people", "population",
    "african american", "african americans",
    "black",
    "south asian", "indian", "pakistani", "bangladeshi", "sri lankan",
    "chinese", "japanese", "korean", "vietnamese", "filipino", "thai",
    "elderly", "older adults"
]

# New keywords you want to add
new_human_terms = [
    "women", "men", "community", "communities",
    "african-americans", "european-americans", "elders"
]

# Combine lists
human_terms += new_human_terms

In [72]:
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()  # lowercase everything
    return any(term in text for term in terms)

In [73]:
df["Human_subjects"] = df["Abstract"].apply(lambda x: check_terms(x, human_terms))

In [74]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [75]:
human_false_with_abstract = df[(df["Human_subjects"] == False) & (df["No_Abstract"] == False)]

In [76]:
print("Number of abstracts with text not flagged as human:", human_false_with_abstract.shape[0])

Number of abstracts with text not flagged as human: 7

In [77]:
print("PMIDs of abstracts not flagged as human:", human_false_with_abstract["PMID"].tolist())

PMIDs of abstracts not flagged as human: [38324147, 37162067, 33239696, 30747852, 23344910, 19202994, 15619403]

In [78]:
# Check if any abstracts are included but US_based = False
non_us_included = df[(df["Final_inclusion"] == True) & (df["US_based"] == False)]

print("Number of non-US papers included:", non_us_included.shape[0])

Number of non-US papers included: 0

In [79]:
import pandas as pd

# Load your master dataset
df = pd.read_csv("master_with_final_inclusion.csv")

In [80]:
# Expanded human_terms list
human_terms = [
    "participant", "participants",
    "patient", "patients",
    "adult", "adults",
    "child", "children",
    "cohort", "subjects",
    "individual", "individuals",
    "volunteer", "volunteers",
    "case", "cases",
    "people", "population",
    "african american", "african americans",
    "black",
    "south asian", "indian", "pakistani", "bangladeshi", "sri lankan",
    "chinese", "japanese", "korean", "vietnamese", "filipino", "thai",
    "elderly", "older adults",
    "women", "men", "community", "communities",
    "african-americans", "european-americans", "elders"
]

# Make sure the function handles NaN and lowercases text
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()
    return any(term in text for term in terms)

# Update Human_subjects column
df["Human_subjects"] = df["Abstract"].apply(lambda x: check_terms(x, human_terms))

In [81]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [82]:
# Only rows with abstracts and Human_subjects = False
human_false_with_abstract = df[(df["Human_subjects"] == False) & (df["No_Abstract"] == False)]

In [83]:
num_nonhuman = human_false_with_abstract.shape[0]
print("Number of abstracts with text not flagged as human:", num_nonhuman)

Number of abstracts with text not flagged as human: 7

In [84]:
df.to_csv("master_with_final_inclusion_updated.csv", index=False)

In [85]:
df_analysis = df[df["Final_inclusion"] == True]
df_analysis.to_csv("final_analysis_dataset_updated.csv", index=False)

In [86]:
# Check if any abstracts are included (Final_inclusion = True) but are non-US
non_us_included = df[(df["Final_inclusion"] == True) & (df["US_based"] == False)]
print("Number of non-US papers included:", non_us_included.shape[0])

Number of non-US papers included: 0

In [87]:
# Rows where Human_subjects = True but US_based = False
human_non_us = df[(df["Human_subjects"] == True) & (df["US_based"] == False)]

In [88]:
print("Number of human abstracts not flagged as US-based:", human_non_us.shape[0])
print("PMIDs:", human_non_us["PMID"].tolist())

Number of human abstracts not flagged as US-based: 0
PMIDs: []

In [89]:
# Filter abstracts with CVD_flag = False
cvd_false = df[(df["CVD_flag"] == False) & (df["No_Abstract"] == False)]
print("Number of abstracts marked as non-CVD:", cvd_false.shape[0])

# Optional: see their PMIDs
print(cvd_false["PMID"].tolist())

# Optional: save for manual review
cvd_false[["PMID", "Title", "Abstract"]].to_csv("cvd_false_check.csv", index=False)

Number of abstracts marked as non-CVD: 790
[41206638, 41191064, 40175212, 39332039, 37418111, 37402594, 36642556, 36394372, 36174763, 36087630, 36069831, 35695540, 35567778, 35429662, 34898338, 34428278, 34278937, 34215559, 33910047, 33694311, 33370152, 33339770, 32898654, 32843499, 32810358, 32682412, 32473908, 32132006, 31866211, 31410783, 30606666, 30205856, 30196971, 30079627, 29956112, 29774391, 29606377, 29506780, 29313298, 29053806, 29040130, 28992354, 28987247, 28898389, 28895842, 28401168, 28338750, 27890336, 27887677, 27831900, 27399601, 27710765, 27670767, 27637377, 27636230, 27549073, 27334066, 27330041, 27147231, 27103765, 26843792, 26541392, 26362830, 26320890, 26098467, 25840504, 25794792, 25783740, 25770035, 25469920, 25361178, 24509026, 24478047, 24443359, 24439988, 24352220, 24310149, 23877973, 23838604, 23495620, 23488580, 23422747, 23215943, 23085727, 22539988, 22381684, 22315308, 22248871, 21986706, 21892017, 21880238, 21859677, 21834039, 21820224, 21814215, 21744966, 21712470, 21700817, 21617122, 21228247, 21220623, 21216853, 20978265, 20801567, 20726280, 20674978, 20625347, 20507203, 20462073, 20448532, 20346335, 20206806, 20014207, 19921264, 19860301, 19809363, 19774332, 19769007, 19539076, 19487639, 19429737, 19386574, 19361593, 19239830, 19132326, 19126923, 19056834, 18785445, 18654123, 18565488, 18535188, 18507275, 18469547, 18447106, 18304554, 18263985, 18186525, 18077654, 18034618, 17942854, 17698506, 17679038, 17634567, 17547873, 17525085, 17258958, 16963396, 16937603, 16697322, 16673837, 16388967, 16355642, 16312942, 16211198, 16210333, 16103755, 16084163, 15954061, 15754274, 15728302, 15689142, 15611892, 15359074, 15334368, 15121368, 15066605, 15051612, 12936900, 12925244, 12785414, 12765972, 12756354, 12728539, 12656446, 12547888, 12482402, 12160187, 12019274, 11465651, 10966211, 10778029, 10636422, 10589324, 10477634, 10353579, 9589242, 9579769, 9424171, 9377284, 9270947, 9164910, 8793257, 8680628, 7979857, 8048420, 7932248, 1502285, 36460591, 35267891, 32768024, 32130575, 31233928, 30403772, 29463611, 28520624, 27460674, 27219306, 27113283, 26927315, 26677257, 23939415, 23470315, 23297873, 23122758, 22621376, 22412857, 20631242, 19659775, 19147658, 17408409, 16259504, 14716320, 41410789, 41400977, 41223940, 41161525, 41135796, 41067700, 41052983, 40962221, 40959884, 40839648, 40832678, 40736354, 40518811, 40468061, 40425193, 40409669, 40407887, 40383504, 40347488, 40215436, 40193077, 40151043, 40139425, 40102521, 40091541, 40085095, 40020979, 39964684, 39922459, 39806755, 39718241, 39528489, 39444110, 39424428, 39379516, 39369931, 39251408, 39193774, 39097853, 39094910, 39088805, 39053837, 38915033, 38908748, 38898146, 38865102, 38833040, 38777093, 38718106, 38692398, 38639339, 38567893, 38519982, 38513200, 38506239, 38482609, 38453275, 38427353, 38423700, 38280106, 39897072, 38090667, 37977914, 37976059, 37968681, 37949472, 37747380, 37746872, 37732628, 37661066, 37635060, 37544493, 37475054, 37424069, 37423490, 37419316, 37300375, 37251686, 37232167, 37162067, 37140127, 37140031, 37138264, 37115419, 37019644, 36915237, 36875358, 36863863, 36862168, 36789947, 36787270, 36645773, 36606683, 36542822, 36375589, 36369635, 36368347, 36316518, 36223235, 35999568, 35947598, 35939163, 35870555, 35852802, 35703388, 35680257, 35674459, 35659624, 35658611, 35623599, 35533896, 35485410, 35483494, 35481809, 35381207, 35371039, 35363103, 35353880, 35348845, 35341693, 35282748, 35267891, 35090972, 35088450, 35062810, 35027577, 35025081, 35012855, 34965764, 34939099, 34913853, 34905011, 34886921, 34876594, 34787635, 34751482, 34469872, 34461752, 34459958, 34410635, 34363329, 34254680, 34212533, 34086103, 33977804, 33956833, 33951529, 33874751, 33850037, 33836779, 33795382, 33737333, 33733963, 33712894, 33649427, 33630467, 33622697, 33599794, 33596847, 33524127, 33522638, 33504366, 33327826, 33315208, 33311530, 33207664, 33148680, 33108398, 33046258, 33026684, 32990574, 32976040, 32858543, 32795776, 32768024, 32749248, 32741597, 32739845, 32707389, 32693707, 32683432, 32674327, 32640463, 32620091, 32552713, 32524500, 32522169, 32496628, 32493099, 32488267, 32475312, 32387378, 32378780, 32375664, 32372168, 32194163, 32163475, 32138662, 32130575, 31910801, 31906704, 31902593, 31898008, 31834153, 31781652, 31767874, 31690524, 31685500, 31655984, 31649215, 31639809, 31638320, 31620815, 31594919, 31583450, 31581860, 31541748, 31539515, 31477383, 31463925, 31406224, 31399476, 31388932, 31373219, 31330075, 31233928, 31130036, 30963702, 30876922, 30861691, 30845157, 30753852, 30747852, 30734418, 30687876, 30682116, 30612117, 30578167, 30499051, 30486859, 30484100, 30419874, 30412074, 30403772, 30401486, 30268398, 30208467, 30126015, 30111889, 30012391, 29982537, 29962360, 29961460, 29853349, 29737561, 29717161, 29712896, 29697588, 29693571, 29690839, 29685249, 29673509, 29624091, 29550249, 29520192, 29463611, 29428535, 29396865, 29191544, 29185181, 29167896, 29148424, 29146987, 29145583, 29141059, 29128033, 29124493, 29024426, 29017598, 28985969, 28967516, 28943488, 28931766, 28859681, 28827610, 28821877, 28797003, 28752678, 28741654, 28646532, 28626947, 28597966, 28592243, 28576267, 28574495, 28554486, 28520624, 28502870, 28487334, 28467138, 28425192, 28420368, 28391406, 28336110, 28315864, 28291093, 28285989, 28207727, 28193259, 28154297, 28151891, 28106903, 28038984, 27995598, 27973921, 27965316, 27914489, 27854313, 27613334, 27549316, 27498821, 27497294, 27491854, 27460674, 27448551, 27389572, 27255797, 27241684, 27074549, 27059529, 27056756, 27043025, 26992166, 26979583, 26965702, 26935158, 26847828, 26823142, 26802477, 26743020, 26677257, 26590913, 26585517, 26530418, 26493032, 26381573, 26296051, 26234222, 26155994, 26149330, 26136283, 26134553, 26124190, 26063595, 26005883, 25972283, 25965592, 25929911, 25840628, 25749433, 25747403, 25671796, 25634196, 25630320, 25616446, 25615550, 25611192, 25488963, 25475605, 25457233, 25375980, 25216506, 25196847, 25096796, 25066630, 25037198, 24979141, 24930933, 24927855, 24887019, 24884708, 24868559, 24781688, 24725169, 24705358, 24685950, 24636277, 24625239, 24585288, 24568795, 24532612, 24527687, 24512748, 24461923, 24458541, 24438044, 24430765, 24402722, 24310866, 24257138, 24195725, 24186879, 24163622, 24146167, 24144269, 24023612, 24015781, 23986082, 23969488, 23958536, 23890849, 23844152, 23816027, 23656904, 23486261, 23470315, 23460156, 23437783, 23411039, 23395514, 23393907, 23216875, 23199534, 23085189, 23065292, 23052434, 22990353, 22990319, 22974298, 22928740, 22849306, 22768891, 22766777, 22706758, 22693240, 22621376, 22615113, 22520931, 22519434, 22476695, 22410630, 22269100, 22234791, 21983153, 21957880, 21862647, 21860558, 21860555, 21799892, 21790921, 21747192, 21714683, 21646495, 21551005, 21430937, 21324549, 21247653, 21095316, 20975728, 20961827, 20813306, 20726280, 20631242, 20605253, 20584707, 20469975, 20456739, 20452405, 20417766, 20395227, 20192982, 20156066, 20054700, 19957002, 19845580, 19666232, 19659775, 19487639, 19390542, 19202994, 19165166, 19147658, 19079148, 19035493, 19022640, 18989256, 18949772, 18937660, 18846901, 18704857, 18556085, 18544106, 18522967, 18441445, 18380209, 18263985, 18082544, 17980740, 17951484, 17928807, 17729373, 17718249, 17707097, 17588403, 17488659, 17408409, 17345096, 17270472, 17249513, 17008328, 16759310, 16340231, 16283999, 16259504, 16221106, 16038014, 15904922, 15881981, 15876942, 15801032, 15725151, 15697074, 15636307, 15633003, 15619404, 15619403, 15201859, 14716320, 14686667, 14646726, 14509898, 12925289, 12925244, 12888056, 12756354, 12660865, 12652227, 12566359, 12547888, 12061285, 11914738, 11840075, 11641532, 11382644, 11260103, 11158401, 11125180, 11120575, 11085787, 10980229, 10966211, 10825765, 10743766, 10713004, 10689861, 9951798, 9868978, 9542780, 9476684, 9363039, 9119510, 8635087, 9248846, 1468851, 30578167, 16283999, 16259504, 12925244]

In [90]:
cvd_terms = [
    # General
    "cardiovascular disease", "cardiovascular diseases", "cvd",
    "heart disease", "heart diseases", "cardiac disease", "cardiac diseases",

    # Coronary / ischemic
    "coronary artery disease", "cad", "ischemic heart disease", "ihd",
    "myocardial infarction", "heart attack",
    "acute coronary syndrome", "acs", "angina",

    # Heart failure
    "heart failure", "congestive heart failure", "chf",
    "cardiomyopathy",

    # Cerebrovascular
    "stroke", "cerebrovascular disease", "cerebrovascular diseases",
    "cerebrovascular accident", "cva",
    "ischemic stroke", "hemorrhagic stroke",
    "transient ischemic attack", "tia",

    # Arrhythmias
    "arrhythmia", "atrial fibrillation", "afib",
    "ventricular tachycardia", "ventricular fibrillation",

    # Vascular
    "atherosclerosis", "arteriosclerosis",
    "peripheral artery disease", "pad",
    "vascular disease", "thrombosis", "embolism",

    # Risk factors
    "hypertension", "high blood pressure",
    "hyperlipidemia", "dyslipidemia", "cholesterol"
]

In [91]:
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()  # lowercase everything
    return any(term in text for term in terms)

In [92]:
df["CVD_flag"] = df["Abstract"].apply(lambda x: check_terms(x, cvd_terms))

In [93]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [94]:
cvd_false_post = df[(df["CVD_flag"] == False) & (df["No_Abstract"] == False)]
print("Remaining non-CVD abstracts:", cvd_false_post.shape[0])
cvd_false_post[["PMID", "Title", "Abstract"]].to_csv("cvd_false_review_post.csv", index=False)

Remaining non-CVD abstracts: 790

In [95]:
# Only abstracts with text, CVD_flag = False
cvd_false = df[(df["CVD_flag"] == False) & (df["No_Abstract"] == False)]
print("Number of non-CVD abstracts with text:", cvd_false.shape[0])

# Optional: see PMIDs
print(cvd_false["PMID"].tolist())

# Optional: save to CSV for review
cvd_false[["PMID", "Title", "Abstract"]].to_csv("cvd_false_review.csv", index=False)

Number of non-CVD abstracts with text: 790
[41206638, 41191064, 40175212, 39332039, 37418111, 37402594, 36642556, 36394372, 36174763, 36087630, 36069831, 35695540, 35567778, 35429662, 34898338, 34428278, 34278937, 34215559, 33910047, 33694311, 33370152, 33339770, 32898654, 32843499, 32810358, 32682412, 32473908, 32132006, 31866211, 31410783, 30606666, 30205856, 30196971, 30079627, 29956112, 29774391, 29606377, 29506780, 29313298, 29053806, 29040130, 28992354, 28987247, 28898389, 28895842, 28401168, 28338750, 27890336, 27887677, 27831900, 27399601, 27710765, 27670767, 27637377, 27636230, 27549073, 27334066, 27330041, 27147231, 27103765, 26843792, 26541392, 26362830, 26320890, 26098467, 25840504, 25794792, 25783740, 25770035, 25469920, 25361178, 24509026, 24478047, 24443359, 24439988, 24352220, 24310149, 23877973, 23838604, 23495620, 23488580, 23422747, 23215943, 23085727, 22539988, 22381684, 22315308, 22248871, 21986706, 21892017, 21880238, 21859677, 21834039, 21820224, 21814215, 21744966, 21712470, 21700817, 21617122, 21228247, 21220623, 21216853, 20978265, 20801567, 20726280, 20674978, 20625347, 20507203, 20462073, 20448532, 20346335, 20206806, 20014207, 19921264, 19860301, 19809363, 19774332, 19769007, 19539076, 19487639, 19429737, 19386574, 19361593, 19239830, 19132326, 19126923, 19056834, 18785445, 18654123, 18565488, 18535188, 18507275, 18469547, 18447106, 18304554, 18263985, 18186525, 18077654, 18034618, 17942854, 17698506, 17679038, 17634567, 17547873, 17525085, 17258958, 16963396, 16937603, 16697322, 16673837, 16388967, 16355642, 16312942, 16211198, 16210333, 16103755, 16084163, 15954061, 15754274, 15728302, 15689142, 15611892, 15359074, 15334368, 15121368, 15066605, 15051612, 12936900, 12925244, 12785414, 12765972, 12756354, 12728539, 12656446, 12547888, 12482402, 12160187, 12019274, 11465651, 10966211, 10778029, 10636422, 10589324, 10477634, 10353579, 9589242, 9579769, 9424171, 9377284, 9270947, 9164910, 8793257, 8680628, 7979857, 8048420, 7932248, 1502285, 36460591, 35267891, 32768024, 32130575, 31233928, 30403772, 29463611, 28520624, 27460674, 27219306, 27113283, 26927315, 26677257, 23939415, 23470315, 23297873, 23122758, 22621376, 22412857, 20631242, 19659775, 19147658, 17408409, 16259504, 14716320, 41410789, 41400977, 41223940, 41161525, 41135796, 41067700, 41052983, 40962221, 40959884, 40839648, 40832678, 40736354, 40518811, 40468061, 40425193, 40409669, 40407887, 40383504, 40347488, 40215436, 40193077, 40151043, 40139425, 40102521, 40091541, 40085095, 40020979, 39964684, 39922459, 39806755, 39718241, 39528489, 39444110, 39424428, 39379516, 39369931, 39251408, 39193774, 39097853, 39094910, 39088805, 39053837, 38915033, 38908748, 38898146, 38865102, 38833040, 38777093, 38718106, 38692398, 38639339, 38567893, 38519982, 38513200, 38506239, 38482609, 38453275, 38427353, 38423700, 38280106, 39897072, 38090667, 37977914, 37976059, 37968681, 37949472, 37747380, 37746872, 37732628, 37661066, 37635060, 37544493, 37475054, 37424069, 37423490, 37419316, 37300375, 37251686, 37232167, 37162067, 37140127, 37140031, 37138264, 37115419, 37019644, 36915237, 36875358, 36863863, 36862168, 36789947, 36787270, 36645773, 36606683, 36542822, 36375589, 36369635, 36368347, 36316518, 36223235, 35999568, 35947598, 35939163, 35870555, 35852802, 35703388, 35680257, 35674459, 35659624, 35658611, 35623599, 35533896, 35485410, 35483494, 35481809, 35381207, 35371039, 35363103, 35353880, 35348845, 35341693, 35282748, 35267891, 35090972, 35088450, 35062810, 35027577, 35025081, 35012855, 34965764, 34939099, 34913853, 34905011, 34886921, 34876594, 34787635, 34751482, 34469872, 34461752, 34459958, 34410635, 34363329, 34254680, 34212533, 34086103, 33977804, 33956833, 33951529, 33874751, 33850037, 33836779, 33795382, 33737333, 33733963, 33712894, 33649427, 33630467, 33622697, 33599794, 33596847, 33524127, 33522638, 33504366, 33327826, 33315208, 33311530, 33207664, 33148680, 33108398, 33046258, 33026684, 32990574, 32976040, 32858543, 32795776, 32768024, 32749248, 32741597, 32739845, 32707389, 32693707, 32683432, 32674327, 32640463, 32620091, 32552713, 32524500, 32522169, 32496628, 32493099, 32488267, 32475312, 32387378, 32378780, 32375664, 32372168, 32194163, 32163475, 32138662, 32130575, 31910801, 31906704, 31902593, 31898008, 31834153, 31781652, 31767874, 31690524, 31685500, 31655984, 31649215, 31639809, 31638320, 31620815, 31594919, 31583450, 31581860, 31541748, 31539515, 31477383, 31463925, 31406224, 31399476, 31388932, 31373219, 31330075, 31233928, 31130036, 30963702, 30876922, 30861691, 30845157, 30753852, 30747852, 30734418, 30687876, 30682116, 30612117, 30578167, 30499051, 30486859, 30484100, 30419874, 30412074, 30403772, 30401486, 30268398, 30208467, 30126015, 30111889, 30012391, 29982537, 29962360, 29961460, 29853349, 29737561, 29717161, 29712896, 29697588, 29693571, 29690839, 29685249, 29673509, 29624091, 29550249, 29520192, 29463611, 29428535, 29396865, 29191544, 29185181, 29167896, 29148424, 29146987, 29145583, 29141059, 29128033, 29124493, 29024426, 29017598, 28985969, 28967516, 28943488, 28931766, 28859681, 28827610, 28821877, 28797003, 28752678, 28741654, 28646532, 28626947, 28597966, 28592243, 28576267, 28574495, 28554486, 28520624, 28502870, 28487334, 28467138, 28425192, 28420368, 28391406, 28336110, 28315864, 28291093, 28285989, 28207727, 28193259, 28154297, 28151891, 28106903, 28038984, 27995598, 27973921, 27965316, 27914489, 27854313, 27613334, 27549316, 27498821, 27497294, 27491854, 27460674, 27448551, 27389572, 27255797, 27241684, 27074549, 27059529, 27056756, 27043025, 26992166, 26979583, 26965702, 26935158, 26847828, 26823142, 26802477, 26743020, 26677257, 26590913, 26585517, 26530418, 26493032, 26381573, 26296051, 26234222, 26155994, 26149330, 26136283, 26134553, 26124190, 26063595, 26005883, 25972283, 25965592, 25929911, 25840628, 25749433, 25747403, 25671796, 25634196, 25630320, 25616446, 25615550, 25611192, 25488963, 25475605, 25457233, 25375980, 25216506, 25196847, 25096796, 25066630, 25037198, 24979141, 24930933, 24927855, 24887019, 24884708, 24868559, 24781688, 24725169, 24705358, 24685950, 24636277, 24625239, 24585288, 24568795, 24532612, 24527687, 24512748, 24461923, 24458541, 24438044, 24430765, 24402722, 24310866, 24257138, 24195725, 24186879, 24163622, 24146167, 24144269, 24023612, 24015781, 23986082, 23969488, 23958536, 23890849, 23844152, 23816027, 23656904, 23486261, 23470315, 23460156, 23437783, 23411039, 23395514, 23393907, 23216875, 23199534, 23085189, 23065292, 23052434, 22990353, 22990319, 22974298, 22928740, 22849306, 22768891, 22766777, 22706758, 22693240, 22621376, 22615113, 22520931, 22519434, 22476695, 22410630, 22269100, 22234791, 21983153, 21957880, 21862647, 21860558, 21860555, 21799892, 21790921, 21747192, 21714683, 21646495, 21551005, 21430937, 21324549, 21247653, 21095316, 20975728, 20961827, 20813306, 20726280, 20631242, 20605253, 20584707, 20469975, 20456739, 20452405, 20417766, 20395227, 20192982, 20156066, 20054700, 19957002, 19845580, 19666232, 19659775, 19487639, 19390542, 19202994, 19165166, 19147658, 19079148, 19035493, 19022640, 18989256, 18949772, 18937660, 18846901, 18704857, 18556085, 18544106, 18522967, 18441445, 18380209, 18263985, 18082544, 17980740, 17951484, 17928807, 17729373, 17718249, 17707097, 17588403, 17488659, 17408409, 17345096, 17270472, 17249513, 17008328, 16759310, 16340231, 16283999, 16259504, 16221106, 16038014, 15904922, 15881981, 15876942, 15801032, 15725151, 15697074, 15636307, 15633003, 15619404, 15619403, 15201859, 14716320, 14686667, 14646726, 14509898, 12925289, 12925244, 12888056, 12756354, 12660865, 12652227, 12566359, 12547888, 12061285, 11914738, 11840075, 11641532, 11382644, 11260103, 11158401, 11125180, 11120575, 11085787, 10980229, 10966211, 10825765, 10743766, 10713004, 10689861, 9951798, 9868978, 9542780, 9476684, 9363039, 9119510, 8635087, 9248846, 1468851, 30578167, 16283999, 16259504, 12925244]

In [96]:
# Take a random sample of, say, 50 abstracts
sample_size = 50
cvd_false_sample = cvd_false.sample(n=sample_size, random_state=42)

# Save for review
cvd_false_sample[["PMID", "Title", "Abstract"]].to_csv("cvd_false_sample_check.csv", index=False)

In [97]:
import pandas as pd

# Load your updated master CSV
df = pd.read_csv("MASTER W UPDATED HUMAN.csv")

# Optional: ensure PMIDs and abstracts are strings
df["PMID"] = df["PMID"].astype(str)
df["Abstract"] = df["Abstract"].astype(str)

In [98]:
cvd_terms = [
    # General / broad
    "cardiovascular disease", "cardiovascular diseases", "cvd",
    "heart disease", "heart diseases", "cardiac disease", "cardiac diseases",
    "cardiovascular risk", "vascular health",

    # Coronary / ischemic
    "coronary artery disease", "cad", "ischemic heart disease", "ihd",
    "myocardial infarction", "heart attack",
    "acute coronary syndrome", "acs", "angina",
    "coronary stenosis", "coronary plaque",

    # Heart failure / cardiomyopathy
    "heart failure", "congestive heart failure", "chf",
    "cardiomyopathy", "dilated cardiomyopathy", "hypertrophic cardiomyopathy",

    # Arrhythmias
    "arrhythmia", "atrial fibrillation", "afib",
    "ventricular tachycardia", "ventricular fibrillation",
    "supraventricular tachycardia", "bradycardia",

    # Cerebrovascular
    "stroke", "ischemic stroke", "hemorrhagic stroke",
    "cerebrovascular disease", "cerebrovascular accident", "cva",
    "transient ischemic attack", "tia", "brain infarction",

    # Peripheral / vascular
    "atherosclerosis", "arteriosclerosis",
    "peripheral artery disease", "pad",
    "vascular disease", "thrombosis", "embolism",
    "arterial occlusion", "venous thromboembolism", "deep vein thrombosis", "dvt",

    # Risk factors (linked to CVD)
    "hypertension", "high blood pressure",
    "hyperlipidemia", "dyslipidemia", "cholesterol",
    "hypertriglyceridemia", "metabolic syndrome", "diabetes mellitus"
]

In [99]:
# Ensure check_terms function is loaded
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()
    return any(term in text for term in terms)

# Apply expanded CVD keyword list
df["CVD_flag"] = df["Abstract"].apply(lambda x: check_terms(x, cvd_terms))

In [100]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [101]:
# Only abstracts with text that are still marked non-CVD
cvd_false = df[(df["CVD_flag"] == False) & (df["No_Abstract"] == False)]
print("Number of abstracts still non-CVD:", cvd_false.shape[0])

Number of abstracts still non-CVD: 686

In [102]:
# Example: sample 50 abstracts for review
sample_size = 50
cvd_false_sample = cvd_false.sample(n=sample_size, random_state=42)

# Save for manual review
cvd_false_sample[["PMID", "Title", "Abstract"]].to_csv("cvd_false_sample_check.csv", index=False)

In [103]:
# Updated master
df.to_csv("master_with_final_inclusion_updated.csv", index=False)

# Final analysis dataset
df[df["Final_inclusion"] == True].to_csv("final_analysis_dataset_updated.csv", index=False)

In [104]:
cvd_terms = [
    # General / broad
    "cardiovascular disease", "cardiovascular diseases", "cvd",
    "heart disease", "heart diseases", "cardiac disease", "cardiac diseases",
    "cardiovascular risk", "vascular health",

    # Coronary / ischemic
    "coronary artery disease", "cad", "ischemic heart disease", "ihd",
    "myocardial infarction", "heart attack",
    "acute coronary syndrome", "acs", "angina",
    "coronary stenosis", "coronary plaque",
    "coronary heart disease", "chd",

    # Heart failure / cardiomyopathy
    "heart failure", "congestive heart failure", "chf",
    "cardiomyopathy", "dilated cardiomyopathy", "hypertrophic cardiomyopathy",
    "left ventricular diastolic function", "lv",

    # Arrhythmias
    "arrhythmia", "atrial fibrillation", "afib",
    "ventricular tachycardia", "ventricular fibrillation",
    "supraventricular tachycardia", "bradycardia",

    # Cerebrovascular
    "stroke", "ischemic stroke", "hemorrhagic stroke",
    "cerebrovascular disease", "cerebrovascular accident", "cva",
    "transient ischemic attack", "tia", "brain infarction",
    "intracranial aneurysm", "intracranial aneurysms",

    # Peripheral / vascular
    "atherosclerosis", "arteriosclerosis",
    "peripheral artery disease", "pad",
    "vascular disease", "thrombosis", "embolism",
    "arterial occlusion", "venous thromboembolism", "deep vein thrombosis", "dvt",

    # Risk factors (linked to CVD)
    "hypertension", "high blood pressure",
    "hyperlipidemia", "dyslipidemia", "cholesterol",
    "hypertriglyceridemia", "metabolic syndrome", "diabetes mellitus",
    "hypertensive"
]

In [105]:
import pandas as pd
df = pd.read_csv("master_with_final_inclusion_updated.csv")

In [106]:
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()
    return any(term in text for term in terms)

df["CVD_flag"] = df["Abstract"].apply(lambda x: check_terms(x, cvd_terms))

In [107]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [108]:
cvd_false = df[(df["CVD_flag"] == False) & (df["No_Abstract"] == False)]
print("Number of remaining non-CVD abstracts:", cvd_false.shape[0])

Number of remaining non-CVD abstracts: 522

In [109]:
df.to_csv("master_with_final_inclusion_updated.csv", index=False)
df[df["Final_inclusion"] == True].to_csv("final_analysis_dataset_updated.csv", index=False)

In [110]:
import pandas as pd
df = pd.read_csv("master_with_final_inclusion_updated.csv")

In [111]:
cvd_terms = [
    # General / broad
    "cardiovascular disease", "cardiovascular diseases", "cvd",
    "heart disease", "heart diseases", "cardiac disease", "cardiac diseases",
    "cardiovascular risk", "vascular health",

    # Coronary / ischemic
    "coronary artery disease", "cad", "ischemic heart disease", "ihd",
    "myocardial infarction", "heart attack",
    "acute coronary syndrome", "acs", "angina",
    "coronary stenosis", "coronary plaque",
    "coronary heart disease", "chd",
    "coronary chronic total occlusion", "cto",
    "percutaneous coronary intervention", "pci",

    # Heart failure / cardiomyopathy
    "heart failure", "congestive heart failure", "chf",
    "cardiomyopathy", "dilated cardiomyopathy", "hypertrophic cardiomyopathy",
    "left ventricular diastolic function", "lv",

    # Arrhythmias
    "arrhythmia", "atrial fibrillation", "afib",
    "ventricular tachycardia", "ventricular fibrillation",
    "supraventricular tachycardia", "bradycardia",

    # Cerebrovascular
    "stroke", "ischemic stroke", "hemorrhagic stroke",
    "cerebrovascular disease", "cerebrovascular accident", "cva",
    "transient ischemic attack", "tia", "brain infarction",
    "intracranial aneurysm", "intracranial aneurysms",

    # Peripheral / vascular
    "atherosclerosis", "arteriosclerosis",
    "peripheral artery disease", "pad",
    "vascular disease", "thrombosis", "embolism",
    "arterial occlusion", "venous thromboembolism", "deep vein thrombosis", "dvt",
    "abdominal aortic aneurysm", "aaa",
    "sinus of valsalva aneurysms", "sov aneurysms",

    # Risk factors (linked to CVD)
    "hypertension", "high blood pressure",
    "hyperlipidemia", "dyslipidemia", "cholesterol",
    "hypertriglyceridemia", "metabolic syndrome", "diabetes mellitus",
    "hypertensive",

    # Major cardiovascular events
    "major acute cardiovascular events", "mace"
]

In [112]:
def check_terms(text, terms):
    if not isinstance(text, str):
        return False
    text = text.lower()
    return any(term in text for term in terms)

df["CVD_flag"] = df["Abstract"].apply(lambda x: check_terms(x, cvd_terms))

In [113]:
df["Final_inclusion"] = (
    (df["Include_in_analysis"] == True) &
    (df["US_based"] == True) &
    (df["Human_subjects"] == True) &
    (df["CVD_flag"] == True)
)

In [114]:
cvd_false = df[(df["CVD_flag"] == False) & (df["No_Abstract"] == False)]
print("Number of remaining non-CVD abstracts:", cvd_false.shape[0])

Number of remaining non-CVD abstracts: 308

In [115]:
df.to_csv("master_with_final_inclusion_updated.csv", index=False)
df[df["Final_inclusion"] == True].to_csv("final_analysis_dataset_updated.csv", index=False)

In [116]:
# Save full master with all flags
df.to_csv("master_with_final_inclusion_updated.csv", index=False)

# Save only the included abstracts for analysis
df[df["Final_inclusion"] == True].to_csv("final_analysis_dataset_updated.csv", index=False)

In [117]:
import pandas as pd

df = pd.read_csv("FINAL FINAL DATASET FOR ANALYSIS.csv")

# Only included studies
df_included = df[df["Final_inclusion"] == True]

In [119]:
non_us_countries = [
    "afghanistan", "albania", "algeria", "andorra", "angola", "antigua", "argentina",
    "armenia", "australia", "austria", "azerbaijan", "bahamas", "bahrain", "bangladesh",
    "barbados", "belarus", "belgium", "belize", "benin", "bhutan", "bolivia", "bosnia",
    "botswana", "brazil", "brunei", "bulgaria", "burkina faso", "burundi", "cambodia",
    "cameroon", "canada", "cape verde", "central african republic", "chad", "chile", "china",
    "colombia", "comoros", "congo", "costa rica", "croatia", "cuba", "cyprus", "czech republic",
    "denmark", "djibouti", "dominica", "dominican republic", "ecuador", "egypt", "el salvador",
    "equatorial guinea", "eritrea", "estonia", "ethiopia", "fiji", "finland", "france", "gabon",
    "gambia", "georgia", "germany", "ghana", "greece", "grenada", "guatemala", "guinea",
    "guinea-bissau", "guyana", "haiti", "honduras", "hungary", "iceland", "india", "indonesia",
    "iran", "iraq", "ireland", "israel", "italy", "ivory coast", "jamaica", "japan", "jordan",
    "kazakhstan", "kenya", "kiribati", "kuwait", "kyrgyzstan", "laos", "latvia", "lebanon",
    "lesotho", "liberia", "libya", "liechtenstein", "lithuania", "luxembourg", "madagascar",
    "malawi", "malaysia", "maldives", "mali", "malta", "marshall islands", "mauritania",
    "mauritius", "mexico", "micronesia", "moldova", "monaco", "mongolia", "montenegro",
    "morocco", "mozambique", "myanmar", "namibia", "nauru", "nepal", "netherlands",
    "new zealand", "nicaragua", "niger", "nigeria", "north korea", "north macedonia", "norway",
    "oman", "pakistan", "palau", "panama", "papua new guinea", "paraguay", "peru", "philippines",
    "poland", "portugal", "qatar", "romania", "russia", "rwanda", "saint kitts", "saint lucia",
    "saint vincent", "samoa", "san marino", "sao tome", "saudi arabia", "senegal", "serbia",
    "seychelles", "sierra leone", "singapore", "slovakia", "slovenia", "solomon islands", "somalia",
    "south africa", "south korea", "spain", "sri lanka", "sudan", "suriname", "sweden", "switzerland",
    "syria", "taiwan", "tajikistan", "tanzania", "thailand", "timor-leste", "togo", "tonga",
    "trinidad", "tunisia", "turkey", "turkmenistan", "tuvalu", "uganda", "uk", "united kingdom",
    "uruguay", "uzbekistan", "vanuatu", "venezuela", "vietnam", "yemen", "zambia", "zimbabwe"
]

In [120]:
def mentions_other_countries(text):
    if not isinstance(text, str):
        return False
    text_lower = text.lower()
    return any(country in text_lower for country in non_us_countries)

df['Mentions_Other_Countries'] = df['Abstract'].apply(mentions_other_countries)

In [121]:
suspect_us_studies = df[(df['US_based'] == True) & (df['Mentions_Other_Countries'] == True)]

print(f"Number of potentially multi-country US studies: {len(suspect_us_studies)}")

# Export for manual review
suspect_us_studies[['PMID', 'Title', 'Abstract']].to_csv("us_suspicious_studies.csv", index=False)

Number of potentially multi-country US studies: 2511

In [123]:
import pandas as pd

# Load your master dataset with all coding
df = pd.read_csv("FINAL FINAL DATASET FOR ANALYSIS.csv")

# Make sure PMIDs are strings (important for matching)
df["PMID"] = df["PMID"].astype(str)

In [124]:
# Replace these with the PMIDs you manually verified as non-US (example PMIDs)
pmids_to_update = ["36537425", "34338063", "32395865"]

# Update the US_based column for these PMIDs
df.loc[df["PMID"].isin(pmids_to_update), "US_based"] = True

In [125]:
# Recalculate final inclusion based on US, Human, CVD flags
df["Final_inclusion"] = (
    df["US_based"] &
    df["Human_subjects"] &
    df["CVD_flag"] &
    df["Include_in_analysis"]  # keep original inclusion logic
)

In [126]:
df.to_csv("Final_inclusion_updated.csv", index=False)
print("✅ Master dataset updated and saved as Final_inclusion_updated.csv")

✅ Master dataset updated and saved as Final_inclusion_updated.csv

In [127]:
# Save the full updated master with flags
df.to_csv("Master_with_flags_updated.csv", index=False)

# Save only the final inclusion dataset
final_cols = [
    "PMID", "Title", "Abstract", "US_based", "Human_subjects", "CVD_flag",
    "Include_in_analysis", "Final_inclusion", "Black_mentions", "South_Asian_mentions",
    "Asian_aggregation", "Disaggregation"
]
df[final_cols].to_csv("Final_inclusion_updated.csv", index=False)

print("✅ Saved both updated datasets:")
print(" - Master_with_flags_updated.csv")
print(" - Final_inclusion_updated.csv")

✅ Saved both updated datasets:
 - Master_with_flags_updated.csv
 - Final_inclusion_updated.csv

In [129]:
import pandas as pd

# Load your master dataset with all coding
df = pd.read_csv("Final_inclusion_updated.csv")

# Make sure PMIDs are strings (important for matching)
df["PMID"] = df["PMID"].astype(str)

In [130]:
# Replace these with the PMIDs you manually verified as non-US (example PMIDs)
pmids_to_update = ["29956112", "28692446", "28185105", "27923154", "27363623"]

# Update the US_based column for these PMIDs
df.loc[df["PMID"].isin(pmids_to_update), "US_based"] = True

In [131]:
# Recalculate final inclusion based on US, Human, CVD flags
df["Final_inclusion"] = (
    df["US_based"] &
    df["Human_subjects"] &
    df["CVD_flag"] &
    df["Include_in_analysis"]  # keep original inclusion logic
)

In [132]:
df.to_csv("ABSOLUTE_Final_inclusion_updated.csv", index=False)
print("✅ Master dataset updated and saved as ABSOLUTE_Final_inclusion_updated.csv")

✅ Master dataset updated and saved as ABSOLUTE_Final_inclusion_updated.csv

In [133]:
# Save the full updated master with flags
df.to_csv("ABSOLUTE_Master_with_flags_updated.csv", index=False)

# Save only the final inclusion dataset
final_cols = [
    "PMID", "Title", "Abstract", "US_based", "Human_subjects", "CVD_flag",
    "Include_in_analysis", "Final_inclusion", "Black_mentions", "South_Asian_mentions",
    "Asian_aggregation", "Disaggregation"
]
df[final_cols].to_csv("ABSOLUTE_Final_inclusion_updated.csv", index=False)

print("✅ Saved both updated datasets:")
print(" - Master_with_flags_updated.csv")
print(" - Final_inclusion_updated.csv")

✅ Saved both updated datasets:
 - Master_with_flags_updated.csv
 - Final_inclusion_updated.csv

In [134]:
import pandas as pd

# Load the final inclusion dataset
df = pd.read_csv("ABSOLUTE_Final_inclusion_updated.csv")

# Ensure PMIDs are strings
df["PMID"] = df["PMID"].astype(str)

# Optional: preview
print(df.head())

       PMID                                              Title  \
0  41491560  Patient Portal Frequency of Use in Patients wi...
1  41402564  Trends in Dementia Associated Mortality among ...
2  41385717  Sociotechnical Needs of Registered Nurses in t...
3  41283203  Burden of Unfair Treatment and Subclinical Ath...
4  41208612  Retrospective cohort analysis of low-molecular...

                                            Abstract  US_based  \
0  electronic health records and patient portals ...      True
1  dementia contributes significantly to morbidit...      True
2  the african american population is disproporti...      True
3  this study examined whether religious coping m...      True
4  venous thromboembolism (vte) is a significant ...      True

   Human_subjects  CVD_flag  Include_in_analysis  Final_inclusion  \
0            True      True                 True             True
1            True      True                 True             True
2            True      True                 True             True
3            True      True                 True             True
4            True      True                 True             True

   Black_mentions  South_Asian_mentions  Asian_aggregation  Disaggregation
0            True                 False              False           False
1            True                 False              False           False
2            True                  True               True           False
3            True                 False              False           False
4            True                 False               True           False

In [135]:
total_included = df["Final_inclusion"].sum()
print(f"Total studies included in analysis: {total_included}")

Total studies included in analysis: 6530

In [136]:
# Black mentions
black_count = df[df["Black_mentions"]==True].shape[0]

# South Asian mentions
sa_count = df[df["South_Asian_mentions"]==True].shape[0]

# Asian aggregation
asian_agg_count = df[df["Asian_aggregation"]==True].shape[0]

# Disaggregation
disagg_count = df[df["Disaggregation"]==True].shape[0]

print(f"Black mentions: {black_count}")
print(f"South Asian mentions: {sa_count}")
print(f"Asian aggregation mentions: {asian_agg_count}")
print(f"Asian disaggregation mentions: {disagg_count}")

Black mentions: 2210
South Asian mentions: 1648
Asian aggregation mentions: 4839
Asian disaggregation mentions: 1700

In [137]:
denominator = df["Final_inclusion"].sum()  # studies included in analysis

print(f"Black proportion: {black_count / denominator:.2%}")
print(f"South Asian proportion: {sa_count / denominator:.2%}")
print(f"Asian aggregation proportion: {asian_agg_count / denominator:.2%}")
print(f"Asian disaggregation proportion: {disagg_count / denominator:.2%}")

Black proportion: 33.84%
South Asian proportion: 25.24%
Asian aggregation proportion: 74.10%
Asian disaggregation proportion: 26.03%

In [138]:
asian_only = df[df["Asian_aggregation"]==True]

disagg_proportion = asian_only["Disaggregation"].sum() / len(asian_only)
print(f"Disaggregation among Asian-focused studies: {disagg_proportion:.2%}")

Disaggregation among Asian-focused studies: 32.38%

In [139]:
import pandas as pd

# Load the original master
original_master = pd.read_csv("master_with_coding.csv")  # replace with your filename

In [140]:
updated_master = pd.read_csv("ABSOLUTE_Master_with_flags_updated.csv")  # the one with US_based, Human, CVD flags

In [142]:
columns_to_restore = ["PMID", "Publication Year", "Authors", "Journal/Book"]

# Merge on PMID
updated_master_full = updated_master.merge(
    original_master[columns_to_restore],
    on="PMID",
    how="left"
)

In [144]:
print(updated_master_full[["PMID", "Publication Year", "Authors", "Journal/Book"]].head())

       PMID  Publication Year  \
0  41491560              2025
1  41402564              2025
2  41385717              2025
3  41283203              2025
4  41208612              2026

                                             Authors             Journal/Book
0  Anderi E, Eisman EB, Bryant A, Hunt T, Mahal M...       J Am Board Fam Med
1  Hassan ST, Onaiz SL, Meghwar S, Ahmed FK, Hyde...  J Epidemiol Glob Health
2  Williams TB, Bimali M, Garza MY, Parker P, Pal...                JMIR Nurs
3  Ashe JJ, Cuevas AG, Skipper AD, Bentley-Edward...         J Am Heart Assoc
4  Chang CY, Hsu CP, Cheng CT, Chen DY, Hsieh MJ,...               Int J Surg

In [145]:
updated_master_full.to_csv("Master_with_flags_complete.csv", index=False)
print("✅ Updated master saved with all flags and restored metadata.")

✅ Updated master saved with all flags and restored metadata.

In [146]:
updated_master_full.to_csv("ABSOLUTE_Master_with_flags_complete.csv", index=False)
print("✅ Updated master saved with all flags and restored metadata.")

✅ Updated master saved with all flags and restored metadata.

In [147]:
final_cols = [
    "PMID", "Title", "Abstract", "Publication Year", "Authors", "Journal/Book",
    "US_based", "Human_subjects", "CVD_flag",
    "Include_in_analysis", "Final_inclusion",
    "Black_mentions", "South_Asian_mentions",
    "Asian_aggregation", "Disaggregation"
]

updated_master_full[final_cols].to_csv("Final_inclusion_updated_complete.csv", index=False)

In [148]:
import pandas as pd

# Load your final inclusion dataset with all flags and metadata
df = pd.read_csv("Final_inclusion_updated_complete.csv")

# Ensure PMIDs are strings and Year is numeric
df["PMID"] = df["PMID"].astype(str)
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

KeyError: 'Year'

In [149]:
import pandas as pd

# Load your final inclusion dataset with all flags and metadata
df = pd.read_csv("Final_inclusion_updated_complete.csv")

# Ensure PMIDs are strings and Year is numeric
df["PMID"] = df["PMID"].astype(str)
df["Publication Year"] = pd.to_numeric(df["Publication Year"], errors="coerce")

In [151]:
# Group by year
yearly = df.groupby("Publication Year").agg(
    total_included=("Final_inclusion", "sum"),
    black_mentions=("Black_mentions", "sum"),
    sa_mentions=("South_Asian_mentions", "sum"),
    asian_agg=("Asian_aggregation", "sum"),
    disagg=("Disaggregation", "sum")
).reset_index()

# Compute proportions
yearly["black_pct"] = yearly["black_mentions"] / yearly["total_included"]
yearly["sa_pct"] = yearly["sa_mentions"] / yearly["total_included"]
yearly["asian_agg_pct"] = yearly["asian_agg"] / yearly["total_included"]
yearly["disagg_pct"] = yearly["disagg"] / yearly["asian_agg"]  # among Asian-focused

print(yearly.head())

   Publication Year  total_included  black_mentions  sa_mentions  asian_agg  \
0              1990               5               1            3          4
1              1991               3               1            0          3
2              1992               7               1            2          6
3              1993              18              10            4          9
4              1994              36               6           21         30

   disagg  black_pct    sa_pct  asian_agg_pct  disagg_pct
0       3   0.200000  0.600000       0.800000    0.750000
1       1   0.333333  0.000000       1.000000    0.333333
2       3   0.142857  0.285714       0.857143    0.500000
3       3   0.555556  0.222222       0.500000    0.333333
4      19   0.166667  0.583333       0.833333    0.633333

In [152]:
yearly.to_csv("population_trends_over_time.csv", index=False)
print("✅ Trends saved to population_trends_over_time.csv")

✅ Trends saved to population_trends_over_time.csv

In [1]:
jupyter nbconvert --to script thesis_H1.ipynb

SyntaxError: invalid syntax (3224570573.py, line 1)

In [2]:
!jupyter nbconvert --to script thesis_H1_pt1.ipynb

[NbConvertApp] WARNING | pattern 'thesis_H1_pt1.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.

In [3]:
!jupyter nbconvert --to script thesis_H1_pt1.ipynb

[NbConvertApp] WARNING | pattern 'thesis_H1_pt1.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.

In [4]:
!jupyter nbconvert --to script "thesis-H1.ipynb"

[NbConvertApp] WARNING | pattern 'thesis-H1.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.

In [5]:
!jupyter nbconvert --to script "thesis_H1_pt1.ipynb"

[NbConvertApp] WARNING | pattern 'thesis_H1_pt1.ipynb' matched no files
This application is used to convert notebook files (*.ipynb)
        to various other formats.

        WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
=======
The options below are convenience aliases to configurable class-options,
as listed in the "Equivalent to" description-line of the aliases.
To see all configurable class-options for some <cmd>, use:
    <cmd> --help-all

--debug
    set log level to logging.DEBUG (maximize logging output)
    Equivalent to: [--Application.log_level=10]
--show-config
    Show the application's configuration (human-readable format)
    Equivalent to: [--Application.show_config=True]
--show-config-json
    Show the application's configuration (json format)
    Equivalent to: [--Application.show_config_json=True]
--generate-config
    generate default config file
    Equivalent to: [--JupyterApp.generate_config=True]
-y
    Answer yes to any questions instead of prompting.
    Equivalent to: [--JupyterApp.answer_yes=True]
--execute
    Execute the notebook prior to export.
    Equivalent to: [--ExecutePreprocessor.enabled=True]
--allow-errors
    Continue notebook execution even if one of the cells throws an error and include the error message in the cell output (the default behaviour is to abort conversion). This flag is only relevant if '--execute' was specified, too.
    Equivalent to: [--ExecutePreprocessor.allow_errors=True]
--stdin
    read a single notebook file from stdin. Write the resulting notebook with default basename 'notebook.*'
    Equivalent to: [--NbConvertApp.from_stdin=True]
--stdout
    Write notebook output to stdout instead of files.
    Equivalent to: [--NbConvertApp.writer_class=StdoutWriter]
--inplace
    Run nbconvert in place, overwriting the existing notebook (only
            relevant when converting to notebook format)
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory=]
--clear-output
    Clear output of current file and save in place,
            overwriting the existing notebook.
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --ClearOutputPreprocessor.enabled=True]
--coalesce-streams
    Coalesce consecutive stdout and stderr outputs into one stream (within each cell).
    Equivalent to: [--NbConvertApp.use_output_suffix=False --NbConvertApp.export_format=notebook --FilesWriter.build_directory= --CoalesceStreamsPreprocessor.enabled=True]
--no-prompt
    Exclude input and output prompts from converted document.
    Equivalent to: [--TemplateExporter.exclude_input_prompt=True --TemplateExporter.exclude_output_prompt=True]
--no-input
    Exclude input cells and output prompts from converted document.
            This mode is ideal for generating code-free reports.
    Equivalent to: [--TemplateExporter.exclude_output_prompt=True --TemplateExporter.exclude_input=True --TemplateExporter.exclude_input_prompt=True]
--allow-chromium-download
    Whether to allow downloading chromium if no suitable version is found on the system.
    Equivalent to: [--WebPDFExporter.allow_chromium_download=True]
--disable-chromium-sandbox
    Disable chromium security sandbox when converting to PDF..
    Equivalent to: [--WebPDFExporter.disable_sandbox=True]
--show-input
    Shows code input. This flag is only useful for dejavu users.
    Equivalent to: [--TemplateExporter.exclude_input=False]
--embed-images
    Embed the images as base64 dataurls in the output. This flag is only useful for the HTML/WebPDF/Slides exports.
    Equivalent to: [--HTMLExporter.embed_images=True]
--sanitize-html
    Whether the HTML in Markdown cells and cell outputs should be sanitized..
    Equivalent to: [--HTMLExporter.sanitize_html=True]
--log-level=<Enum>
    Set the log level by value or name.
    Choices: any of [0, 10, 20, 30, 40, 50, 'DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL']
    Default: 30
    Equivalent to: [--Application.log_level]
--config=<Unicode>
    Full path of a config file.
    Default: ''
    Equivalent to: [--JupyterApp.config_file]
--to=<Unicode>
    The export format to be used, either one of the built-in formats
            ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf']
            or a dotted object name that represents the import path for an
            ``Exporter`` class
    Default: ''
    Equivalent to: [--NbConvertApp.export_format]
--template=<Unicode>
    Name of the template to use
    Default: ''
    Equivalent to: [--TemplateExporter.template_name]
--template-file=<Unicode>
    Name of the template file to use
    Default: None
    Equivalent to: [--TemplateExporter.template_file]
--theme=<Unicode>
    Template specific theme(e.g. the name of a JupyterLab CSS theme distributed
    as prebuilt extension for the lab template)
    Default: 'light'
    Equivalent to: [--HTMLExporter.theme]
--sanitize_html=<Bool>
    Whether the HTML in Markdown cells and cell outputs should be sanitized.This
    should be set to True by nbviewer or similar tools.
    Default: False
    Equivalent to: [--HTMLExporter.sanitize_html]
--writer=<DottedObjectName>
    Writer class used to write the
                                        results of the conversion
    Default: 'FilesWriter'
    Equivalent to: [--NbConvertApp.writer_class]
--post=<DottedOrNone>
    PostProcessor class used to write the
                                        results of the conversion
    Default: ''
    Equivalent to: [--NbConvertApp.postprocessor_class]
--output=<Unicode>
    Overwrite base name use for output files.
                Supports pattern replacements '{notebook_name}'.
    Default: '{notebook_name}'
    Equivalent to: [--NbConvertApp.output_base]
--output-dir=<Unicode>
    Directory to write output(s) to. Defaults
                                  to output to the directory of each notebook. To recover
                                  previous default behaviour (outputting to the current
                                  working directory) use . as the flag value.
    Default: ''
    Equivalent to: [--FilesWriter.build_directory]
--reveal-prefix=<Unicode>
    The URL prefix for reveal.js (version 3.x).
            This defaults to the reveal CDN, but can be any url pointing to a copy
            of reveal.js.
            For speaker notes to work, this must be a relative path to a local
            copy of reveal.js: e.g., "reveal.js".
            If a relative path is given, it must be a subdirectory of the
            current directory (from which the server is run).
            See the usage documentation
            (https://nbconvert.readthedocs.io/en/latest/usage.html#reveal-js-html-slideshow)
            for more details.
    Default: ''
    Equivalent to: [--SlidesExporter.reveal_url_prefix]
--nbformat=<Enum>
    The nbformat version to write.
            Use this to downgrade notebooks.
    Choices: any of [1, 2, 3, 4]
    Default: 4
    Equivalent to: [--NotebookExporter.nbformat_version]

Examples
--------

    The simplest way to use nbconvert is

            > jupyter nbconvert mynotebook.ipynb --to html

            Options include ['asciidoc', 'custom', 'html', 'latex', 'markdown', 'notebook', 'pdf', 'python', 'qtpdf', 'qtpng', 'rst', 'script', 'slides', 'webpdf'].

            > jupyter nbconvert --to latex mynotebook.ipynb

            Both HTML and LaTeX support multiple output templates. LaTeX includes
            'base', 'article' and 'report'.  HTML includes 'basic', 'lab' and
            'classic'. You can specify the flavor of the format used.

            > jupyter nbconvert --to html --template lab mynotebook.ipynb

            You can also pipe the output to stdout, rather than a file

            > jupyter nbconvert mynotebook.ipynb --stdout

            PDF is generated via latex

            > jupyter nbconvert mynotebook.ipynb --to pdf

            You can get (and serve) a Reveal.js-powered slideshow

            > jupyter nbconvert myslides.ipynb --to slides --post serve

            Multiple notebooks can be given at the command line in a couple of
            different ways:

            > jupyter nbconvert notebook*.ipynb
            > jupyter nbconvert notebook1.ipynb notebook2.ipynb

            or you can specify the notebooks list in a config file, containing::

                c.NbConvertApp.notebooks = ["my_notebook.ipynb"]

            > jupyter nbconvert --config mycfg.py

To see all available configurables, use `--help-all`.